In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('WeekByWeekRankings2020to2025.csv')
df
df_copy = df.copy()

In [5]:
df1 = pd.read_csv('CollegeFootballRankings24to20.csv')
df1
df_copy = df.copy()

In [6]:
df

AP_rank            Team  Week  year
0           1         Georgia     1  2024
1           2      Ohio State     1  2024
2           3          Oregon     1  2024
3           4           Texas     1  2024
4           5         Alabama     1  2024
...       ...             ...   ...   ...
1970       21             USC    16  2020
1971       22           Miami    16  2020
1972       23      Ball State    16  2020
1973       24  San José State    16  2020
1974       25         Buffalo    16  2020

[1975 rows x 4 columns]

In [9]:
df['AP_rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [10]:
df['AP_rank'].value_counts()

AP_rank
8     81
11    81
3     80
16    80
2     80
21    80
7     79
1     79
5     79
23    79
24    79
6     79
13    79
15    79
14    79
18    79
10    79
25    79
20    79
19    79
17    78
22    78
4     77
9     77
12    77
Name: count, dtype: int64

In [11]:
df['AP_rank'].isna().sum()

np.int64(0)

In [12]:
df['Team'].isna().sum()

np.int64(0)

In [13]:
df['Team'].unique()

array(['Georgia', 'Ohio State', 'Oregon', 'Texas', 'Alabama', 'Ole Miss',
       'Notre Dame', 'Michigan', 'Penn State', 'Florida State',
       'Missouri', 'LSU', 'Utah', 'Clemson', 'Tennessee', 'Oklahoma',
       'Kansas State', 'Oklahoma State', 'Miami', 'Texas A&M', 'Arizona',
       'NC State', 'USC', 'Kansas', 'Iowa', 'Louisville', 'Washington',
       'Iowa State', 'Nebraska', 'Memphis', 'UNLV', 'Illinois', 'BYU',
       'Indiana', 'Boise State', 'Pittsburgh', 'SMU', 'Army', 'Navy',
       'Vanderbilt', 'Washington State', 'Colorado', 'South Carolina',
       'Tulane', 'Arizona State', 'Syracuse', 'TCU', 'Oregon State',
       'North Carolina', 'Wisconsin', 'Texas Tech', 'Duke', 'UCLA',
       'Florida', 'Kentucky', 'Fresno State', 'Air Force',
       'James Madison', 'Liberty', 'Toledo', 'West Virginia', 'Baylor',
       'Michigan State', 'Wake Forest', 'Cincinnati', 'Arkansas',
       'Houston', 'Minnesota', 'Mississippi State', 'UCF',
       'Coastal Carolina', 'UTSA', 'Troy'

In [14]:
df['Team'].value_counts()

Team
Georgia              79
Alabama              79
Ohio State           78
Oregon               74
Notre Dame           71
                     ..
West Virginia         1
Utah State            1
Appalachian State     1
Ball State            1
San José State        1
Name: count, Length: 85, dtype: int64

In [15]:
df['Week'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [16]:
df['Week'].isna().sum()

np.int64(0)

In [17]:
df['Week'].value_counts()

Week
1     125
3     125
4     125
5     125
7     125
6     125
8     125
9     125
13    125
10    125
11    125
12    125
15    125
14    125
16    125
2     100
Name: count, dtype: int64

In [20]:
df['year'].unique()

array([2024, 2023, 2022, 2021, 2020])