In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('CollegeFootballRankings2025.csv')
# df

In [3]:
df['Team'].isna().sum()

np.int64(0)

In [4]:
df['Team'].value_counts()

Team
Florida Gators                    13
Georgia Bulldogs                  13
Pittsburgh Panthers               13
Texas A&M Aggies                  13
California Golden Bears           13
Auburn Tigers                     13
Air Force Falcons                 12
Akron Zips                        12
Arkansas State Red Wolves         12
Arkansas Razorbacks               12
Arizona Wildcats                  12
Arizona State Sun Devils          12
App State Mountaineers            12
Alabama Crimson Tide              12
Boise State Broncos               12
Boston College Eagles             12
Buffalo Bulls                     12
BYU Cougars                       12
Central Michigan Chippewas        12
Charlotte 49ers                   12
Cincinnati Bearcats               12
Clemson Tigers                    12
Ball State Cardinals              12
Army Black Knights                12
Colorado Buffaloes                12
Coastal Carolina Chanticleers     12
Duke Blue Devils                 

In [5]:
unique_team = df['Team'].unique()
unique_team = sorted(unique_team)
unique_team

['Air Force Falcons',
 'Akron Zips',
 'Alabama Crimson Tide',
 'App State Mountaineers',
 'Arizona State Sun Devils',
 'Arizona Wildcats',
 'Arkansas Razorbacks',
 'Arkansas State Red Wolves',
 'Army Black Knights',
 'Auburn Tigers',
 'BYU Cougars',
 'Ball State Cardinals',
 'Baylor Bears',
 'Boise State Broncos',
 'Boston College Eagles',
 'Bowling Green Falcons',
 'Buffalo Bulls',
 'California Golden Bears',
 'Central Michigan Chippewas',
 'Charlotte 49ers',
 'Cincinnati Bearcats',
 'Clemson Tigers',
 'Coastal Carolina Chanticleers',
 'Colorado Buffaloes',
 'Colorado State Rams',
 'Delaware Blue Hens',
 'Duke Blue Devils',
 'East Carolina Pirates',
 'Eastern Michigan Eagles',
 'Florida Atlantic Owls',
 'Florida Gators',
 'Florida International Panthers',
 'Florida State Seminoles',
 'Fresno State Bulldogs',
 'Georgia Bulldogs',
 'Georgia Southern Eagles',
 'Georgia State Panthers',
 'Georgia Tech Yellow Jackets',
 "Hawai'i Rainbow Warriors",
 'Houston Cougars',
 'Illinois Fighting Il

In [6]:
df['date'].isna().sum()

np.int64(0)

In [8]:
df['date'].unique()

array(['Sat, Aug 30', 'Sat, Sep 13', 'Sat, Sep 20', 'Sat, Sep 27',
       'Sat, Oct 4', 'Sat, Oct 11', 'Sat, Oct 18', 'Sat, Nov 1',
       'Sat, Nov 15', 'Sat, Nov 22', 'Fri, Nov 28', 'Thu, Aug 28',
       'Sat, Sep 6', 'Tue, Nov 4', 'Tue, Nov 11', 'Tue, Nov 18',
       'Fri, Aug 29', 'Thu, Nov 6', 'Fri, Sep 26', 'Fri, Sep 12',
       'Tue, Oct 14', 'Sat, Oct 25', 'Thu, Nov 20', 'Thu, Sep 25',
       'Sat, Nov 8', 'Sat, Dec 13', 'Fri, Sep 5', 'Fri, Oct 24',
       'Wed, Nov 12', 'Wed, Nov 19', 'Fri, Oct 3', 'Fri, Oct 17',
       'Thu, Sep 18', 'Fri, Nov 14', 'Sat, Nov 29', 'Thu, Oct 30',
       'Fri, Oct 10', 'Wed, Oct 15', 'Wed, Oct 22', 'Thu, Oct 9',
       'Thu, Oct 16', 'Tue, Oct 21', 'Wed, Oct 29', 'Fri, Nov 21',
       'Sat, Aug 23', 'Thu, Oct 23', 'Fri, Sep 19', 'Tue, Oct 28',
       'Wed, Oct 8', 'Fri, Oct 31', 'Fri, Nov 7', 'Thu, Nov 27',
       'Sun, Aug 31', 'Thu, Sep 11', 'Thu, Oct 2', 'Mon, Sep 1',
       'Thu, Nov 13', 'Wed, Nov 5', 'Tue, Nov 25'], dtype=object)

In [9]:
df['date'].value_counts()

date
Sat, Sep 6     127
Sat, Nov 22    109
Sat, Sep 13    107
Sat, Sep 20    105
Sat, Nov 29    102
Sat, Nov 15    101
Sat, Oct 11     99
Sat, Oct 18     99
Sat, Sep 27     96
Sat, Oct 25     90
Sat, Oct 4      89
Sat, Nov 8      86
Sat, Nov 1      86
Sat, Aug 30     86
Fri, Nov 28     26
Thu, Aug 28     24
Fri, Aug 29     19
Fri, Oct 3      10
Sat, Aug 23      9
Fri, Oct 17      8
Fri, Sep 12      8
Thu, Oct 9       8
Fri, Oct 24      7
Fri, Sep 5       6
Tue, Oct 14      6
Fri, Sep 26      6
Tue, Nov 18      6
Fri, Nov 7       6
Fri, Oct 31      6
Fri, Oct 10      6
Wed, Nov 12      6
Tue, Nov 11      4
Tue, Nov 4       4
Tue, Oct 21      4
Thu, Nov 6       4
Wed, Nov 5       4
Tue, Oct 28      4
Wed, Oct 22      4
Thu, Oct 30      4
Wed, Oct 29      4
Fri, Nov 14      4
Wed, Oct 15      4
Wed, Nov 19      4
Wed, Oct 8       4
Sun, Aug 31      4
Tue, Nov 25      4
Fri, Sep 19      4
Fri, Nov 21      3
Sat, Dec 13      2
Thu, Nov 20      2
Thu, Sep 25      2
Thu, Oct 16      2
Thu, Se

In [10]:
df['opponent'].isna().sum()

np.int64(0)

In [11]:
df['opponent'].value_counts().sort_index()

opponent
Abilene Christian            2
Air Force                   11
Akron                       11
Alabama                     11
Alabama A&M                  1
Alabama State                1
Alcorn State                 1
App State                   11
Arizona                     11
Arizona State               11
Arkansas                    11
Arkansas State              11
Arkansas-Pine Bluff          1
Army                        11
Auburn                      12
Austin Peay                  2
BYU                         11
Ball State                  11
Baylor                      11
Bethune-Cookman              2
Boise State                 11
Boston College              11
Bowling Green               11
Bryant                       2
Bucknell                     1
Buffalo                     11
Cal Poly                     1
California                  11
Campbell                     1
Central Arkansas             1
Central Connecticut          1
Central Michigan            11

In [13]:
unique_opponent = df['opponent'].unique()
unique_opponent = sorted(unique_opponent)
unique_opponent

['Abilene Christian',
 'Air Force',
 'Akron',
 'Alabama',
 'Alabama A&M',
 'Alabama State',
 'Alcorn State',
 'App State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Arkansas-Pine Bluff',
 'Army',
 'Auburn',
 'Austin Peay',
 'BYU',
 'Ball State',
 'Baylor',
 'Bethune-Cookman',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Bryant',
 'Bucknell',
 'Buffalo',
 'Cal Poly',
 'California',
 'Campbell',
 'Central Arkansas',
 'Central Connecticut',
 'Central Michigan',
 'Charleston Southern',
 'Charlotte',
 'Chattanooga',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colgate',
 'Colorado',
 'Colorado State',
 'Delaware',
 'Delaware State',
 'Duke',
 'Duquesne',
 'East Carolina',
 'East Tennessee State',
 'East Texas A&M',
 'Eastern Illinois',
 'Eastern Kentucky',
 'Eastern Michigan',
 'Eastern Washington',
 'Elon',
 'Florida',
 'Florida A&M',
 'Florida Atlantic',
 'Florida International',
 'Florida State',
 'Fordham',
 'Fresno State',
 'Furman',
 'Gardner-Webb'

In [14]:
df['win_loss'].isna().sum()

np.int64(0)

In [15]:
df['win_loss'].unique()

array(['W', 'L', 'N'], dtype=object)

In [16]:
df['win_loss'].value_counts()

win_loss
N    928
W    410
L    300
Name: count, dtype: int64

In [17]:
df['pass'].isna().sum()

np.int64(0)

In [18]:
df['pass'].unique()

array([112, 246, 278, 212,  43,  30,  63,  20,  33, 139,  54, 282, 219,
        51, 252,  16,  22,  21,  11, 254, 226, 382, 276, 340, 180,  14,
       368, 294, 217,  64, 218,  47, 257,  82, 188, 221, 291, 101, 161,
       373, 178, 253, 376,  74, 322, 239, 305, 325, 207, 206, 345, 125,
       222, 285, 248,  32, 129,  52,  36,  41, 116,  23, 534, 108, 251,
       142, 220, 242,  25,  87,  71, 105, 209, 185,  26, 419, 440, 211,
       250, 393, 225, 307, 321, 215, 136,  68, 268, 390, 333, 197,  89,
        57, 109, 274, 146, 131, 170, 107, 133, 318, 104, 272,  97, 175,
       179, 351, 234, 267, 279, 208, 245,  17,  59, 241, 138, 134, 140,
       186, 150,   8,  60,  69, 388, 214, 230, 196, 363, 249, 163, 102,
       172,  28, 159, 158, 204, 304, 119,  91, 132, 176, 155,  78, 270,
       312, 265, 314,  40,  24, 389, 334, 313, 269, 366, 293,  45, 189,
       330, 168, 228, 309, 343, 290, 287,  61, 298, 141, 187, 127, 184,
       203, 100,  44, 152, 237, 205,  29, 121, 240, 190, 227, 13

In [19]:
df['pass'].value_counts()

pass
20     51
26     37
14     37
36     28
29     26
24     25
28     25
25     25
32     23
30     22
18     22
21     22
17     21
33     20
9      19
16     18
22     18
74     17
52     17
79     14
11     14
41     14
67     13
57     13
37     12
95     11
8      11
47     11
63     10
60     10
13     10
7      10
87     10
38     10
97     10
34     10
49     10
144     9
45      9
245     9
180     9
78      9
51      9
155     8
55      8
219     7
223     7
10      7
270     7
254     7
125     7
128     7
94      7
209     7
148     7
175     7
71      7
102     7
237     6
48      6
130     6
70      6
218     6
72      6
208     6
179     6
279     6
176     6
40      6
119     6
91      6
101     6
275     6
161     6
90      6
53      6
222     6
65      5
106     5
252     5
164     5
217     5
188     5
88      5
133     5
142     5
170     5
345     5
178     5
189     5
134     5
44      5
196     5
249     5
59      5
230     5
136     5
68      5
61      5
197  

In [20]:
df['rush'].isna().sum()

np.int64(0)

In [21]:
df['rush'].unique()

array([ 66,  72, 110, 139, 152,  43,  30,  63,  20,  33,  64,  81, 161,
        22, 176,  16,  21,  11,  31,  76,  25,  46, 136, 180,  14, 111,
       194,  95, 113,  98,  47,  73, 144,  80, 134, 101, 125,  51, 189,
        85,  34,  74,  79, 151, 115,  70, 206,  42,  38,  83,  61,  23,
        92,  32, 100, 124, 117, 127, 116,  54, 534, 137, 121, 119,  28,
       242,  10, 154,  86,  96,  26, 135,  65,  44, 123, 171,  69,  39,
        68,  52,  48,  55,  57,  59,  89,  41,  75, 106, 131,  90, 122,
        67,  17, 102,  18, 108,  49,  15,   8,  60,  40, 112, 130, 249,
        27,  97,  84,  91, 103,  78, 179,  24, 168,  36,  58,  45, 126,
        71, 105, 104,  93, 107, 163, 141, 173,  82,  29, 167, 165, 128,
        13, 156,  37,  50, 132,  53, 109, 148,  56, 195, 120, 147,  99,
        94, 129, 175, 166, 114, 138,  62,   6, 204,   7, 159, 149, 199,
       372, 143, 250, 193,  35, 140,  77, 157,  87, 345,  12,  88,  19,
         9, 162, 142, 487, 153, 186, 146, 177, 150, 174, 264, 37

In [22]:
df['rec'].isna().sum()

np.int64(928)

In [23]:
df['rec'].unique()

array([ 83.,  63., 177., 116., 166.,  nan,  47.,  28.,  99.,  65.,  16.,
       125., 146.,  67., 165.,  98., 134., 142., 132.,  20., 140., 141.,
        68., 105.,  78., 126.,  50., 168.,  37.,  92., 121.,  74.,  81.,
       102.,  73.,  85., 114.,  64.,  26.,  48.,  77.,  88.,  56.,  42.,
        33.,  61., 151.,  71., 155.,  58.,  87.,  84., 138.,  90.,  70.,
        32.,  80.,  38.,  46.,  51., 117., 136.,  97.,  49., 161.,  69.,
        60.,  91.,  23., 106.,  59., 122., 228.,  93.,  41., 109., 128.,
        66., 118., 108.,  36.,  54.,  35.,  39., 120.,  89.,  79.,  55.,
        72., 104.,  62.,  76., 131., 110.,  22., 111.,  27., 173., 112.,
       147.,  43.,  82.,  95.,  75.,  52., 172.,  44., 144.,  53.,  86.,
       186., 207.,  13.,  24., 130., 214., 103.,  94.,  34.,  29.,  19.,
         5., 154., 135., 170., 113.,  57.,  30., 127., 107., 133.,  96.,
        25., 123.,  40., 243., 149.,  45., 145., 157., 115., 119., 153.,
       183., 101., 158., 179., 100., 189., 152., 25

In [24]:
df['points_allowed'].isna().sum()

np.int64(928)

In [25]:
df['points_allowed'].unique()

array([13., 49., 44., 34., nan, 10., 68., 31.,  7., 45., 22.,  0., 14.,
       21., 11., 38., 47., 23., 19., 24., 15.,  6.,  3., 17., 39., 41.,
       32., 56., 28., 30., 16., 42., 29., 27., 37., 48., 40., 35., 20.,
       63., 54., 36., 33., 52., 55., 18., 26.,  9., 51., 46., 59., 70.,
       12., 62., 66., 73., 25., 69., 43.])

In [26]:
df['points_scored'].isna().sum()

np.int64(928)

In [27]:
df['points_scored'].unique()

array([49., 30., 37., 35., 31., nan,  0., 28., 51.,  3., 17., 73., 38.,
       24., 34., 20., 22., 14., 27., 40., 48., 23., 41., 52., 56., 13.,
       42., 16., 21.,  6., 10., 25., 45.,  7., 47., 66., 26., 69., 11.,
       70., 44., 19., 55., 29., 77., 36., 59., 43., 63., 15., 39., 46.,
        9., 12., 54., 32., 61., 68., 33., 60., 18., 72., 67., 62.])

In [28]:
df['point_differential'].isna().sum()

np.int64(928)

In [29]:
df['point_differential'].unique()

array([ 36., -19., -12.,  -9.,  -3.,  nan, -10., -68.,  44., -42.,   6.,
       -14.,  73.,  24.,   3.,  16.,  23.,   7., -16., -33.,   4.,  19.,
        -4.,  34.,  45., -25.,  28.,  42.,  -6.,  -1., -43.,  18.,  -8.,
        -7.,   1., -22.,  14.,  39., -31., -39.,   5.,  35., -27.,  37.,
        12.,  33., -21.,  56.,  -2., -41.,  10., -23., -15., -13.,  69.,
        21.,  32.,  13., -34., -24.,   2., -28., -60.,  11., -17., -11.,
        70.,   8., -38., -40.,  17.,  22., -26.,  53.,  38.,  -5., -32.,
       -29.,  55.,  74.,   9.,  49., -56., -49.,  47.,  20.,  27.,  26.,
       -53.,  40.,  48.,  25.,  31., -47., -48., -44., -18.,  46., -36.,
        29.,  60., -20.,  66.,  63.,  68.,  52., -35.,  51.,  43.,  15.,
       -66.,  41.,  50., -55., -37.,  61., -73.,  54.])

In [30]:
df['point_differential'].value_counts().sort_index()

point_differential
-73.0     1
-68.0     1
-66.0     1
-60.0     2
-56.0     2
-55.0     1
-53.0     1
-49.0     2
-48.0     1
-47.0     1
-44.0     1
-43.0     1
-42.0     3
-41.0     3
-40.0     2
-39.0     4
-38.0     4
-37.0     1
-36.0     1
-35.0     6
-34.0     6
-33.0     2
-32.0     4
-31.0     4
-29.0     1
-28.0     9
-27.0     2
-26.0     3
-25.0     7
-24.0    10
-23.0     3
-22.0     6
-21.0     6
-20.0     4
-19.0     8
-18.0     9
-17.0    15
-16.0     7
-15.0     2
-14.0    14
-13.0     6
-12.0     3
-11.0     9
-10.0    10
-9.0      3
-8.0      7
-7.0     25
-6.0     11
-5.0      5
-4.0      6
-3.0     33
-2.0      7
-1.0     14
 1.0     13
 2.0      9
 3.0     36
 4.0      7
 5.0      5
 6.0     11
 7.0     28
 8.0      7
 9.0      3
 10.0    10
 11.0     9
 12.0     4
 13.0     7
 14.0    15
 15.0     2
 16.0     9
 17.0    19
 18.0    13
 19.0    10
 20.0     5
 21.0     9
 22.0     7
 23.0     3
 24.0    13
 25.0     8
 26.0     3
 27.0     5
 28.0    14
 29.0    

In [31]:
df['home_game'].isna().sum()

np.int64(0)

In [32]:
df['home_game'].unique()

array([ True, False])

In [33]:
df['home_game'].value_counts()

home_game
True     891
False    747
Name: count, dtype: int64

In [34]:
df['season'].isna().sum()

np.int64(0)

In [35]:
df['season'].unique()

array([2025])

In [36]:
df['CONF'].isna().sum()

np.int64(0)

In [37]:
df['CONF'].unique()

array(['Mountain West', 'MAC', 'SEC', 'Sun Belt', 'Big 12', 'American',
       'ACC', 'CUSA', 'Big Ten', 'FBS Indep.', 'Pac-12'], dtype=object)

In [38]:
df['SOR'].isna().sum()

np.int64(0)

In [39]:
df['SOR'].unique()

array([130, 122,  10,  89,  24,  40,  76, 119,  94,  33,  95,  47,  58,
       127,  98, 116,  13,  61,  96, 131,  20,  86,  92, 103, 129,  87,
        49,  69, 133, 109,  53, 110,  36,  42,  12,  93, 118,  11,  75,
        38,   9,   8,  46,  22, 113,  50,  48, 105,  78, 117,  60, 123,
       115,  45,  37,  16, 114,  44, 134,  18, 104,   2,  52,  17, 128,
        59,  41,  97,  14,  39,  51,  29, 124,  67,  99, 100,  25, 125,
        63,  31,  85,   3,   6, 121,  32,   5,   4,  79,  81,  77, 112,
        71,  62, 108,  64, 132,  43,  19,  82,  83,  56,  30,  68,  27,
         1,  55,  80,   7,  90,  70,  23, 120, 111,  72, 106,  91,  66,
        26,  34,  57,  35, 126, 102,  15,  28, 101,  73,  21,  65,  84,
        54,  88,  74, 107])

In [40]:
df['FPI'].isna().sum()

np.int64(0)

In [41]:
df['FPI'].unique()

array([103, 133,   3, 109,  34,  47,  41, 114,  88,  23, 120,  43,  52,
        82,  95, 115,  20,  79, 126, 132,  38,  40, 122,  59, 112, 104,
        33,  56, 127, 107,  26, 129,  24,  80,   6, 105, 121,  42, 102,
        63,  28,   4,  35,  31,  97,  64,  30,  44, 118, 136,  50, 110,
       106,  76,  37,  17,  93,  53, 135,  32,  87,   9,  61,  12, 131,
        66,  45, 119,  18,  73,  58,  22, 123,  83, 130,  98,  60, 111,
        67,   5,  74,   1,  15, 113,  46,   7,   2,  96,  19,  48,  70,
       117,  51, 134,  85,  91,  39, 100,  29,  49,  89,  86,  69,  25,
        92,  11,  13,   8,  71,  14,  62,  90,  57, 128, 125,  55,  78,
        72, 124,  65,  10,  75,  21, 116,  84,  16,  36,  68,  81,  27,
       101,  77,  94,  99,  54, 108])

In [42]:
df['AP/CFP'].isna().sum()

np.int64(0)

In [43]:
df['AP/CFP'].unique()

array(['--', '8', '21', '18', '25', '10', '13', '17', '7', '22', '11',
       '23', '2', '15', '14', '16', '1', '6', '4', '3', '24', '12', '5',
       '9', '20', '19'], dtype=object)

In [44]:
df['SOS'].isna().sum()

np.int64(0)

In [45]:
df['SOS'].unique()

array([117,  94,   3, 120,  49,  99,   5, 103,  84,   7,  68,  59,  29,
        95,  60, 130, 105, 112,  63, 126,  38,  58,  71,  42, 100, 123,
        77,  93, 118, 108,   1,  76,  10, 111,  11,  36,   9, 102, 114,
        88,  12,  70,  27,  67, 119, 116,  50,  56,  55,   2,   4, 104,
        89,  86,  92,  17,  62, 113,  43, 127,  97,  15,  20,  24, 121,
        31,  30,  41, 109, 136,  78,  69,  61,  57, 131,  80, 132, 101,
        51,   8,  39,  34,  64,  21,  47,  44,  48,  14,  79, 122,  13,
       128, 110,  53, 135,  54,  83,  75,  25,  26, 125,  35,  22,  72,
        74,  45,  18,  16, 107,  81, 124,  96,  32, 106,  66,  91,  37,
       134,  40, 133,  82,  23,  85,  52,  65,  28,  73,  46, 115,  33,
        98,  19, 129,  87,   6,  90])

In [46]:
df['GC'].isna().sum()

np.int64(0)

In [47]:
df['GC'].unique()

array([127, 121,  11,  98,  43,  35,  34, 130, 104,  24, 125,  77,  47,
        90,  96, 123,  17,  89,  99, 135,  22,  75, 116,  54, 132,  95,
        67,  64, 133, 102,  28, 109,  27,  80,  18, 101,  84,  51,  82,
        74,  13,   7,  42,  44, 106,  60,  32,  62,  59,  94,  50, 131,
       128,  39,  55,  21,  76,   6, 122,  56,  86,   1,  52,  16, 136,
        71,  29,  92,  25,  68,  61,  31, 112,  93, 113, 105,  48, 111,
        63,   8,  70,   4,   5, 124,  15,  10,   3, 119,  53,  33,  73,
       126,  38, 134,  78,  91,  46, 120,  40,  37,  85, 107,  81,  23,
        97,  12,   9,  36,  69,   2,  45, 110,  30, 114, 118,  58, 108,
        65,  88,  66,  19,  49,  26, 129,  72,  14,  20,  87,  57,  41,
        83, 103, 115, 100,  79, 117])

In [48]:
df['AVGWP'].isna().sum()

np.int64(0)

In [49]:
df['AVGWP'].unique()

array([112, 108,  39,  82,  58,  23,  69, 119, 111,  61, 131,  84,  66,
        95, 110,  81,  10,  76,  99, 133,  25,  89, 123,  65, 134,  71,
        79,  53, 128,  94,  67, 104,  41,  64,  30, 113, 117,  45,  54,
        72,  34,   5,  60,  49,  92,  47,  33,  73,  51, 132,  86, 126,
       118,  29,  46,  43,  70,   3, 129,  26,  87,   2,  74,  31, 135,
        80,  35, 102,   8,  13,  56,  14, 116, 101,  78, 105,  18, 107,
        63,  32,  75,   6,   4, 130,  15,  12,   7, 127,  37,   9,  98,
        91,  22, 136,  40,  90,  42, 120,  59,  52,  57, 124, 106,  20,
        96,  11,  19,  55,  62,   1,  21, 103,  44, 100, 115,  48, 125,
        27,  88,  38,  17,  68,  24, 121,  85,  28,  16,  93,  36,  50,
        83, 122,  77,  97, 109, 114])