In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_csv('CollegeFootballRankings2025.csv')
df

In [3]:
df['Team'].isna().sum()

np.int64(0)

In [4]:
df['Team'].value_counts()

Team
Utah State Aggies                 12
Hawai'i Rainbow Warriors          12
Washington State Cougars          11
Nevada Wolf Pack                  11
Air Force Falcons                 10
Liberty Flames                    10
Louisiana Tech Bulldogs           10
Oregon State Beavers              10
UNLV Rebels                       10
Wyoming Cowboys                   10
Sam Houston Bearkats               9
UConn Huskies                      9
UTEP Miners                        9
San José State Spartans            9
Western Kentucky Hilltoppers       9
San Diego State Aztecs             9
New Mexico Lobos                   9
New Mexico State Aggies            9
Middle Tennessee Blue Raiders      9
Florida International Panthers     9
Missouri State Bears               9
Kennesaw State Owls                9
Georgia Bulldogs                   9
Navy Midshipmen                    9
Ole Miss Rebels                    8
Jacksonville State Gamecocks       8
Colorado State Rams              

In [5]:
unique_team = df['Team'].unique()
unique_team = sorted(unique_team)
unique_team

['Air Force Falcons',
 'Akron Zips',
 'Alabama Crimson Tide',
 'App State Mountaineers',
 'Arizona State Sun Devils',
 'Arizona Wildcats',
 'Arkansas Razorbacks',
 'Arkansas State Red Wolves',
 'Army Black Knights',
 'Auburn Tigers',
 'BYU Cougars',
 'Ball State Cardinals',
 'Baylor Bears',
 'Boise State Broncos',
 'Boston College Eagles',
 'Bowling Green Falcons',
 'Buffalo Bulls',
 'California Golden Bears',
 'Central Michigan Chippewas',
 'Charlotte 49ers',
 'Cincinnati Bearcats',
 'Clemson Tigers',
 'Coastal Carolina Chanticleers',
 'Colorado Buffaloes',
 'Colorado State Rams',
 'Delaware Blue Hens',
 'Duke Blue Devils',
 'East Carolina Pirates',
 'Eastern Michigan Eagles',
 'Florida Atlantic Owls',
 'Florida Gators',
 'Florida International Panthers',
 'Florida State Seminoles',
 'Fresno State Bulldogs',
 'Georgia Bulldogs',
 'Georgia Southern Eagles',
 'Georgia State Panthers',
 'Georgia Tech Yellow Jackets',
 "Hawai'i Rainbow Warriors",
 'Houston Cougars',
 'Illinois Fighting Il

In [6]:
df['date'].isna().sum()

np.int64(0)

In [7]:
df['date'].unique()

array(['Sat, Aug 30', 'Sat, Sep 13', 'Sat, Sep 20', 'Sat, Sep 27',
       'Sat, Oct 4', 'Sat, Oct 11', 'Sat, Oct 18', 'Sat, Nov 1',
       'Sat, Nov 15', 'Sat, Nov 22', 'Sat, Sep 6', 'Fri, Aug 29',
       'Fri, Sep 26', 'Fri, Sep 12', 'Sat, Oct 25', 'Sat, Nov 8',
       'Sat, Dec 13', 'Fri, Sep 5', 'Fri, Oct 24', 'Fri, Nov 28',
       'Fri, Oct 3', 'Fri, Oct 17', 'Fri, Nov 14', 'Sat, Nov 29',
       'Fri, Oct 10', 'Fri, Nov 21', 'Sat, Aug 23', 'Fri, Sep 19',
       'Fri, Oct 31', 'Fri, Nov 7'], dtype=object)

In [8]:
df['date'].value_counts()

date
Sat, Sep 6     127
Sat, Sep 13    107
Sat, Sep 20    105
Sat, Aug 30     86
Sat, Sep 27     84
Sat, Nov 22     27
Sat, Nov 15     25
Sat, Nov 8      25
Sat, Oct 11     24
Sat, Oct 4      22
Sat, Nov 29     22
Fri, Nov 28     20
Sat, Nov 1      20
Fri, Aug 29     19
Sat, Oct 25     14
Sat, Oct 18     13
Fri, Oct 3      10
Sat, Aug 23      9
Fri, Oct 17      8
Fri, Sep 12      8
Fri, Sep 26      6
Fri, Sep 5       6
Fri, Oct 31      6
Fri, Oct 24      6
Fri, Oct 10      6
Fri, Nov 7       4
Fri, Nov 14      4
Fri, Nov 21      3
Sat, Dec 13      2
Fri, Sep 19      2
Name: count, dtype: int64

In [9]:
df['opponent'].isna().sum()

np.int64(0)

In [11]:
df['opponent'].value_counts().sort_index()

opponent
 Alabama                     5
 Arizona State               1
 Auburn                      3
 Clemson                     3
 Florida                     1
 Florida State               3
 Georgia                     6
 Georgia                     2
 Georgia Tech                3
 Georgia Tech                1
 Illinois                    3
 Indiana                     4
 Iowa State                  3
 Iowa State                  1
 Kansas State                1
 LSU                         4
 Miami                       3
 Michigan                    5
 Missouri                    5
 Notre Dame                  7
 Ohio State                  3
 Oklahoma                    5
 Oklahoma                    1
 Ole Miss                    7
 Oregon                      5
 Penn State                  3
 SMU                         1
 South Carolina              1
 South Florida               1
 Tennessee                   4
 Tennessee                   1
 Texas                       6

In [13]:
unique_opponent = df['opponent'].unique()
unique_opponent = sorted(unique_opponent)
unique_opponent

[' Alabama',
 ' Arizona State',
 ' Auburn',
 ' Clemson',
 ' Florida',
 ' Florida State',
 ' Georgia',
 ' Georgia ',
 ' Georgia Tech',
 ' Georgia Tech ',
 ' Illinois',
 ' Indiana',
 ' Iowa State',
 ' Iowa State ',
 ' Kansas State ',
 ' LSU',
 ' Miami',
 ' Michigan',
 ' Missouri',
 ' Notre Dame',
 ' Ohio State',
 ' Oklahoma',
 ' Oklahoma ',
 ' Ole Miss',
 ' Oregon',
 ' Penn State',
 ' SMU',
 ' South Carolina',
 ' South Florida',
 ' Tennessee',
 ' Tennessee ',
 ' Texas',
 ' Texas ',
 ' Texas A&M',
 ' Texas Tech',
 ' USC',
 ' Utah',
 ' Vanderbilt',
 'Abilene Christian',
 'Air Force',
 'Akron',
 'Alabama A&M',
 'Alcorn State',
 'App State',
 'App State ',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Arkansas-Pine Bluff',
 'Army',
 'Army ',
 'Auburn',
 'Austin Peay',
 'BYU',
 'Ball State',
 'Baylor',
 'Bethune-Cookman',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Bryant',
 'Bucknell',
 'Buffalo',
 'Cal Poly',
 'California',
 'Campbell',
 'Central Connecticut',
 

In [14]:
df['win_loss'].isna().sum()

np.int64(0)

In [15]:
df['win_loss'].unique()

array(['W', 'L', 'N'], dtype=object)

In [16]:
df['win_loss'].value_counts()

win_loss
N    458
W    225
L    137
Name: count, dtype: int64

In [17]:
df['pass'].isna().sum()

np.int64(458)

In [18]:
df['pass'].unique()

array(['112', nan, '54', '282', '254', '226', '382', '368', '294', '217',
       '257', '82', '188', '161', '373', '178', '322', '239', '305',
       '345', '125', '222', '129', '52', '108', '251', '142', '87', '71',
       '105', '419', '440', '211', '307', '268', '390', '333', '274',
       '146', '133', '318', '97', '175', '234', '267', '279', '59', '89',
       '36', '140', '253', '230', '196', '207', '163', '102', '172',
       '159', '158', '204', '180', '132', '312', '265', '334', '313',
       '314', '293', '248', '189', '330', '228', '309', '343', 'Jr.',
       '287', '187', '127', '184', '152', '237', '179', '176', '121',
       '240', '190', '227', '304', 'IV', '201', '150', '143', '210',
       '157', '296', '193', '245', '270', '44', '83', '183', '278', '134',
       'III', '280', '223', '273', '88', 'II', '118', '116', '85', '149',
       '197', '335', '194', '86', '5', '126', '50', '182', '151', '232',
       '220', '100', 'Rio-Wilson', '258', '261', '205', '56', '199',


In [21]:
df['pass'].value_counts()

pass
178           5
217           4
222           4
257           4
142           4
279           4
227           4
270           4
155           4
251           3
282           3
305           3
274           3
Jr.           3
176           3
189           3
152           3
240           3
184           3
304           3
211           3
97            3
IV            3
196           3
382           3
193           3
108           3
52            3
134           3
235           3
209           3
295           3
170           3
218           3
247           3
174           3
245           3
223           3
88            3
293           2
248           2
125           2
133           2
318           2
121           2
230           2
287           2
309           2
265           2
334           2
179           2
333           2
172           2
254           2
112           2
294           2
373           2
75            2
266           2
341           2
83            2
278           2
50 

In [22]:
df['rush'].isna().sum()

np.int64(458)

In [23]:
df['rush'].unique()

array(['66', '72', nan, '64', '81', '31', '76', '25', '111', '194', '95',
       '73', '110', '144', '125', '51', '189', 'Jr.', '151', '115', '42',
       '38', '83', '100', '124', '137', '121', '119', '63', '10', '154',
       '54', '135', '123', '48', '55', '59', '98', '75', '131', '122',
       '102', '18', '49', '40', '16', '112', '80', '27', '92', '68', '47',
       '179', '30', '78', '58', '44', '105', '104', '93', '46', '71',
       '173', '34', '167', '86', '90', '69', '41', '128', '65', '156',
       '103', '45', '60', '132', '89', '101', '109', '56', 'III', '116',
       '195', '120', '99', '61', '129', '114', '82', '22', '126', '74',
       '24', '67', 'Rio-Wilson', '50', '94', '39', '28', '113', '85',
       '159', '143', '250', '180', '193', '140', '33', '141', '17', '52',
       '148', 'II', '77', '91', '79', '87', '108', '163', '138', '62',
       '136', '12', '43', '37', '35', '88', 'IV', '96', '127', '107',
       '57', '20', '21', '157', '186', '142', '147', '36', '11

In [24]:
df['rec'].isna().sum()

np.int64(458)

In [25]:
df['rec'].unique()

array(['83', '63', nan, '28', '99', '146', '67', '165', '134', '142',
       '132', '141', '68', '105', '50', '168', '37', '121', '74', '81',
       '85', '64', '26', '77', 'Jr.', '42', '33', '151', '138', '90',
       '80', 'II', '117', '47', '84', 'Jesus', '60', '61', '56', '122',
       '228', '109', '106', '36', '54', '39', '120', '79', '49', '161',
       '88', '136', '87', '62', 'III', '27', '66', '173', '43', '82',
       '95', '76', '73', '55', '75', '70', '52', '97', '172', '48', '72',
       '69', '125', '108', '128', '53', '13', '46', '92', '24', '38',
       '78', '103', '19', '5', '59', '94', '58', '41', '89', '93', '91',
       '65', '133', '40', '149', '104', '71', '98', '44', '119', '153',
       '101', '34', 'Gladding', '86', '51', '158', '116', '45', '189',
       '126', '152', '57', '112', 'IV', '21', '114', '207', '32', '155',
       '123', '100', '135', '22', '131', '115', '147', '124', '127',
       '148', '113', '110', '102'], dtype=object)

In [26]:
df['points_allowed'].isna().sum()

np.int64(458)

In [27]:
df['points_allowed'].unique()

array([ 13.,  49.,  nan,  68.,  31.,   0.,  14.,  11.,  38.,  19.,  24.,
        15.,   6.,   3.,  17.,   7.,  41.,  56.,  30.,  21.,  42.,  29.,
       452.,  10.,  34.,  28.,  45.,  63.,  20.,  35.,  16.,  48.,  27.,
        36.,  52.,  39.,  18.,   9.,  59.,  12.,  40.,  23.,  62.,  47.,
       402.,  73.,  46.,  22.,  37.,  69.,  26.,  33.,  44.,  43.])

In [28]:
df['points_scored'].isna().sum()

np.int64(458)

In [29]:
df['points_scored'].unique()

array([ 49.,  30.,  nan,   0.,  28.,  17.,  73.,  38.,  34.,  20.,  22.,
        40.,  48.,  23.,  52.,  56.,  35.,  42.,  14.,  16., 272.,  24.,
        31.,   3.,  51.,  66., 402.,  45.,  69.,  27.,  11.,  70.,  10.,
        21.,   7.,  13.,  44.,  19.,  55.,  77.,  36.,  41.,  37.,  59.,
         6.,  47.,  46.,   9.,  12.,  39.,  26.,  63.,  68.,  32.,  33.,
        54.,  15.,  61.,  60., 452.,  18.,  72.,  43.,  67.,  62.])

In [30]:
df['point_differential'].isna().sum()

np.int64(458)

In [31]:
df['point_differential'].unique()

array([  36.,  -19.,   nan,  -68.,   -3.,  -14.,   73.,   24.,   23.,
          7.,  -16.,   19.,   -4.,   34.,   45.,    6.,   42.,   -6.,
         18.,  -42.,   -8.,  242.,    3.,   14.,   39.,   16.,  -31.,
        -39.,    5., -404.,   35.,   37.,   56.,  360.,  -10.,   10.,
         69.,   32.,   13.,    2.,  -28.,  -60.,  -23.,  -17.,   70.,
         -7.,   11.,  -41.,  -38.,    4.,  -24.,  -26.,   53.,   38.,
        -25.,   -5.,  -32.,   55.,   -2.,   33.,  -34.,   74.,   28.,
          9.,   49.,   22.,  -56.,  -22.,   47.,   17.,   20.,   26.,
         27.,   40.,   48.,    8.,  -11.,   -1.,  -47.,  -48.,   25.,
         21.,   31.,  -40., -360.,   60.,  -20.,    1.,   66.,  -13.,
         63.,  -18.,   68.,   52.,  -35.,   51.,  -66.,   46.,   -9.,
         50.,   29.,  404.,  -37.,  -21.,   61.,  -33.,  -73.,   12.,
         54.,  -12.,   41.,  -49.])

In [33]:
df['point_differential'].value_counts().sort_index()

point_differential
-404.0     1
-360.0     1
-73.0      1
-68.0      1
-66.0      1
-60.0      2
-56.0      1
-49.0      1
-48.0      1
-47.0      1
-42.0      2
-41.0      1
-40.0      1
-39.0      3
-38.0      3
-37.0      1
-35.0      2
-34.0      2
-33.0      1
-32.0      3
-31.0      3
-28.0      4
-26.0      2
-25.0      4
-24.0      7
-23.0      2
-22.0      2
-21.0      1
-20.0      3
-19.0      6
-18.0      2
-17.0      9
-16.0      5
-14.0      5
-13.0      2
-12.0      1
-11.0      4
-10.0      5
-9.0       1
-8.0       2
-7.0      12
-6.0       2
-5.0       1
-4.0       2
-3.0      10
-2.0       4
-1.0       5
 1.0       5
 2.0       5
 3.0      13
 4.0       3
 5.0       1
 6.0       2
 7.0      15
 8.0       2
 9.0       1
 10.0      6
 11.0      4
 12.0      1
 13.0      3
 14.0      6
 16.0      7
 17.0     12
 18.0      5
 19.0      7
 20.0      3
 21.0      4
 22.0      3
 23.0      2
 24.0     10
 25.0      5
 26.0      2
 27.0      2
 28.0      7
 29.0      1
 31.0 

In [34]:
df['home_game'].isna().sum()

np.int64(0)

In [35]:
df['home_game'].unique()

array([ True, False])

In [36]:
df['home_game'].value_counts()

home_game
True     475
False    345
Name: count, dtype: int64

In [37]:
df['season'].isna().sum()

np.int64(0)

In [38]:
df['season'].unique()

array([2025])

In [39]:
df['CONF'].isna().sum()

np.int64(0)

In [40]:
df['CONF'].unique()

array(['Mountain West', 'MAC', 'SEC', 'Sun Belt', 'Big 12', 'American',
       'ACC', 'CUSA', 'Big Ten', 'FBS Indep.', 'Pac-12'], dtype=object)

In [41]:
df['SOR'].isna().sum()

np.int64(0)

In [42]:
df['SOR'].unique()

array([110, 126,  38,  95,  57,  24,  59, 100,  69,  12, 105,  31,  86,
       119,  67,  84,  32,  22,  74, 125,  60,  82, 115,  99,  96,  65,
        98,  79, 122, 111,  58,   3,  49,   2,  81, 109,  10,  56,  23,
        19,  25,  89,  11, 104,  88,  48, 118, 113, 120,  41, 121, 116,
        66,  34,   4, 117,  36,  30,   7,  26,  53, 108,  78,  16,  71,
        15,  45,  13,  18, 114,  43,  94,  73,  39,  93, 102,  61,   5,
         8,  77,  33,   6,  20,  40,  87,  63,  64,  29, 112,  72, 107,
        51,  14,  75,  90,  54,  28,  80,  37,   1,  47,  46,  52,  68,
       106,  17, 123,  92,  44, 124,  97,  35,  21,  55,  27, 103, 101,
         9,  83,  91,  42,  76,  62,  85,  50,  70])

In [43]:
df['FPI'].isna().sum()

np.int64(0)

In [44]:
df['FPI'].unique()

array([113, 134,   3, 102,  32,  38,  24, 106,  81,  20, 131,  39,  61,
        62,  88, 111,  22,  59, 129, 132,  46,  30, 127,  58,  92, 117,
        63,  52, 123, 103,  28,  96,  27,  75,   4,  97, 119,  33, 110,
        48,  23,  16,  40,  34,  87,  77,  31,  50, 125, 135,  41, 100,
       109,  86,  43,  19, 104,  60, 136,  36,  90,  11,  69,  10, 130,
        55,  42, 121,  12,  68,  53,  17, 122,  85, 133,  83,  67,  95,
        76,  14,  72,   2,  13,  89,  56,   8,   1, 101,   7,  57,  79,
       114,  44, 124, 118, 112,  35,  80,  37,  54,  94,  74,  70,  25,
        99,   9,  15,   6,  71,  26,  66,  91,  47, 126, 120,  49,  93,
        84, 128,  65,   5,  82,  18, 107,  78,  21,  51,  73,  98,  29,
       115,  64, 105, 116,  45, 108])

In [45]:
df['AP/CFP'].isna().sum()

np.int64(0)

In [46]:
df['AP/CFP'].unique()

array(['--', '14', '22', '7', '5', '18', '9', '19', '12', '3', '4', '21',
       '23', '24', '1', '11', '13', '6', '2', '15', '10', '8', '17', '25',
       '16', '20'], dtype=object)

In [47]:
df['SOS'].isna().sum()

np.int64(0)

In [48]:
df['SOS'].unique()

array([116,  45,  50, 127,  68, 114,  27,  29,  66,  72,  39,  40,  69,
        79,  85,  95, 120, 112,  13, 126,  57,  24,  75,  61,  46,  87,
        47,  96,  63,  88,  34,  20,   9,  74,  26,   8,  11,  65,  71,
       113, 101, 117,  80,  82,  78,  64,  33,  58,  42,  56,  48, 111,
        41,  53, 125,  36,  17, 130,  76, 122,  12,  55, 118,  30,  77,
        93,  91,   7,  92, 135,  84, 100,  18,  22, 124,  86, 133,  83,
        10,   1,   3,  49,  59,   2,  23,  43,  99,  37, 134, 105,  54,
       109, 121, 102, 132,   5,  97,  31,  67,   6, 103,  44,  38, 108,
        70,  28,  19,  14,  60, 136,  81,  51,  90, 123, 110, 131,  52,
       104,   4, 129, 107,  35, 119,  16,  32,  62,  94,  25, 115, 128,
        98,  89, 106,  21,  15,  73])

In [49]:
df['GC'].isna().sum()

np.int64(0)

In [50]:
df['GC'].unique()

array([114, 129,  33, 121,  44,  15,  34,  88,  72,   7, 124,  76,  54,
        74,  80, 119,  10,  42, 117, 136,  37,  79, 127,  78, 113, 115,
       105,  77, 133, 123,  46,  51,   3,  85,  20,  93,  89,  43,  87,
        39,  19,  13,  55,  49,  92,  38,  18,  96,  95, 109,  30, 132,
       118,  56,  48,  28,  66,  21, 130,  36, 103,   5,  47,  35, 134,
        61,  26, 116,  27,  82,  65,  17, 110,  71, 128,  73,  83, 102,
        86,  40,  67,   6,   4,  57,  31,  16,   1, 126,  11,  45,  58,
       101,  25, 135, 122, 111,  53,  98,  69,  60,  81,  99,  97,  14,
        91,   9,  24,  32,  68,   2,  52, 106,  12, 125, 120,  59, 131,
        75,  63,  62,   8,  50,  22,  94,  70,  29,  41, 112,  84,  23,
       104,  90, 107, 108,  64, 100])

In [51]:
df['AVGWP'].isna().sum()

np.int64(0)

In [52]:
df['AVGWP'].unique()

array([ 87, 129,  48,  72,  50,   9,  47, 103,  97,  17, 126,  92,  71,
        78,  68,  88,   2,  25, 131, 122,  37, 100, 120,  85, 124,  91,
       114,  63, 135, 106,  62,  66,   6,  75,  39, 118, 108,  49,  67,
        28,  20,   5,  46,  43,  95,  53,  33,  94, 105,  99,  36, 123,
       113,  65,  27,  52,  77,   8, 119,  29, 136,   7,  24,  55, 134,
        45,  23, 127,  21,  34,  64,  15, 102,  93,  86,  57,  40, 107,
       111, 104, 117,  12,  13, 101,  59,  35,   4, 130,   3,  31,  58,
        60,  14, 133,  80, 128,  38, 109,  69, 115,  54, 116,  96,  16,
        73,  18,  44,  56,  89,   1,  51, 110,  19,  84,  83,  26, 132,
        61,  98,  30,  11,  70,  22, 112,  90,  41,  32, 121,  42,  10,
        82,  74,  76, 125,  79,  81])