In [12]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
# pd.reset_option('all')

In [ ]:
df = pd.read_csv('CollegeFootballRankings24to20.csv')
df

In [33]:
for i in df:
    print(i)

Team
date
Team_id
opponent
win_loss
OT
OT_num
pass
rush
rec
points_allowed
points_scored
point_differential
home_game
week
season
CONF
SOR
FPI
AP/CFP
SOS
GC
AVGWP


In [ ]:
df['Team'].unique()
team_unique = df['Team'].unique()
team_unique = sorted(team_unique)
team_unique

In [ ]:
df['Team'].value_counts().sort_index()

In [27]:
df['Team'].isna().sum()

np.int64(0)

In [28]:
df['date'].isna().sum()

np.int64(0)

In [29]:
df['date'].nunique()

390

In [ ]:
df['date'].value_counts()
date_unique = df['date'].unique()
date_unique = sorted(date_unique)
date_unique

In [ ]:
df['date'].value_counts().sort_index()

In [34]:
df['Team_id'].isna().sum()

np.int64(0)

In [ ]:
team_id_unique = df['Team_id'].unique()
team_id_unique = sorted(team_id_unique)
team_id_unique

In [36]:
df['Team_id'].value_counts()

Team_id
154     132
87       75
61       75
333      75
349      74
153      73
228      73
251      73
249      72
98       72
66       72
290      71
194      71
2636     71
99       71
201      71
252      71
97       70
324      70
57       70
276      70
235      70
2655     70
2306     70
2633     70
197      70
2426     70
142      70
344      69
213      69
2032     69
221      69
2390     69
145      69
309      69
2116     68
2641     68
2653     68
2132     68
8        68
96       68
150      68
2628     68
239      68
245      68
2        68
2335     68
23       67
130      67
68       67
59       67
2294     67
326      67
2579     67
2567     67
6        67
2483     66
275      66
52       66
277      66
135      66
238      66
103      66
278      66
2348     66
2305     66
5        66
62       65
30       65
21       65
2638     65
2005     65
2433     65
2247     65
164      65
2439     65
158      65
356      65
183      65
77       65
58       65
259      64
2751    

In [37]:
df['opponent'].isna().sum()

np.int64(0)

In [38]:
df['opponent'].value_counts()

opponent
Bye                         762
Notre Dame                   66
Texas                        65
Georgia                      64
Alabama                      64
NC State                     64
Michigan                     62
Ohio State                   62
Clemson                      62
Penn State                   62
UTSA                         61
Louisville                   61
Tulane                       61
Oklahoma State               60
Pittsburgh                   60
Oklahoma                     60
Western Kentucky             60
Iowa State                   60
Iowa                         60
Florida                      59
Ole Miss                     59
LSU                          59
Missouri                     59
Duke                         59
Louisiana                    59
Syracuse                     58
BYU                          58
Virginia Tech                58
TCU                          58
Oregon                       58
Boise State                  58

In [40]:
opponent_unique = df['opponent'].unique()
opponent_unique = sorted(opponent_unique)
opponent_unique

['Abilene Christian',
 'Air Force',
 'Akron',
 'Alabama',
 'Alabama A&M',
 'Alabama State',
 'Albany',
 'Alcorn State',
 'App State',
 'Appalachian State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Arkansas-Pine Bluff',
 'Army',
 'Auburn',
 'Austin Peay',
 'BYU',
 'Ball State',
 'Baylor',
 'Bethune-Cookman',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Bryant',
 'Bucknell',
 'Buffalo',
 'Bye',
 'Cal Poly',
 'California',
 'Campbell',
 'Central Arkansas',
 'Central Connecticut',
 'Central Michigan',
 'Charleston Southern',
 'Charlotte',
 'Chattanooga',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colgate',
 'Colorado',
 'Colorado State',
 'Delaware',
 'Delaware State',
 'Duke',
 'Duquesne',
 'East Carolina',
 'East Tennessee State',
 'East Texas A&M',
 'Eastern Illinois',
 'Eastern Kentucky',
 'Eastern Michigan',
 'Eastern Washington',
 'Elon',
 'Florida',
 'Florida A&M',
 'Florida Atlantic',
 'Florida International',
 'Florida State',
 'Fordham',
 '

In [41]:
for i in df:
    print(i)

Team
date
Team_id
opponent
win_loss
OT
OT_num
pass
rush
rec
points_allowed
points_scored
point_differential
home_game
week
season
CONF
SOR
FPI
AP/CFP
SOS
GC
AVGWP


In [42]:
df['win_loss'].isna().sum()

np.int64(0)

In [43]:
df['win_loss'].value_counts()

win_loss
W      4103
L      3683
Bye     762
Name: count, dtype: int64

In [45]:
win_loss_unique = df['win_loss'].unique()
win_loss_unique = sorted(win_loss_unique)
win_loss_unique

['Bye', 'L', 'W']

In [46]:
df['OT'].isna().sum()

np.int64(0)

In [47]:
df['OT'].unique()

array([False,  True])

In [48]:
df['OT'].value_counts()

OT
False    8218
True      330
Name: count, dtype: int64

In [49]:
df['OT_num'].isna().sum()

np.int64(8218)

In [50]:
df['OT_num'].unique()

array([nan,  3.,  1.,  2.,  4.,  6.,  8.,  7.,  5.,  9.])

In [51]:
df['OT_num'].value_counts()

OT_num
1.0    202
2.0     91
4.0     16
3.0     12
6.0      2
8.0      2
5.0      2
9.0      2
7.0      1
Name: count, dtype: int64

In [52]:
unique_OT_num = df['OT_num'].unique()
unique_OT_num = sorted(unique_OT_num)
unique_OT_num

[np.float64(nan),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(6.0),
 np.float64(7.0),
 np.float64(8.0),
 np.float64(9.0)]

In [53]:
df['pass'].isna().sum()

np.int64(16)

In [ ]:
df['pass'].unique()

In [ ]:
unique_pass = df['pass'].unique()
unique_pass = sorted(unique_pass)
unique_pass

In [ ]:
df['pass'].value_counts()

In [61]:
for i in df:
    print(i)

Team
date
Team_id
opponent
win_loss
OT
OT_num
pass
rush
rec
points_allowed
points_scored
point_differential
home_game
week
season
CONF
SOR
FPI
AP/CFP
SOS
GC
AVGWP


In [62]:
df['rush'].isna().sum()

np.int64(1)

In [63]:
df['rush'].unique()

array([ 34.,  78.,  20.,  15.,  83., 122.,  14., 101.,  29.,  62.,  32.,
        58.,  66.,  45.,  87., 111.,  65.,  31.,  41.,  47.,  84., 140.,
        63.,  19.,  23.,  10.,  37.,  42.,  27.,  30., 112.,  26., 126.,
        69.,  77.,  61., 139.,  52.,  81.,  74.,  46., 120.,  54., 106.,
        67.,  89.,  79.,  86.,  70., 180.,  40.,  71.,  38., 102.,  21.,
       136., 103.,  53.,  39.,  75.,  48., 163.,  59.,  80.,   4.,  82.,
        73.,  49.,  64.,  55.,  28.,  44.,  43.,  60., 118.,  33.,  17.,
       189.,  95.,  72.,  12., 105.,  92.,  90.,  24., 173.,  22., 135.,
        50., 150., 132., 162.,  68., 156.,  93., 119., 178.,  88., 152.,
       206., 191., 149.,  56.,  98.,  96., 107., 113., 104., 114., 108.,
       128.,  57.,  36.,  35.,  94., 116., 100., 176., 133.,  76., 130.,
       240.,  99.,  51.,  91., 158., 199., 221., 177., 134.,  11., 137.,
       141., 145., 193., 167., 185., 168., 146., 153., 165.,  97., 117.,
       110., 109., 234., 125., 115., 147., 175., 12

In [64]:
df['rush'].value_counts()

rush
0.0      762
60.0      90
67.0      85
49.0      83
68.0      83
57.0      82
63.0      82
76.0      80
71.0      80
78.0      80
64.0      80
80.0      79
82.0      78
65.0      78
87.0      77
74.0      77
69.0      77
52.0      77
54.0      77
39.0      76
62.0      75
104.0     75
53.0      75
66.0      74
75.0      74
83.0      74
42.0      73
55.0      73
73.0      73
81.0      73
58.0      71
61.0      70
43.0      70
50.0      69
48.0      69
45.0      69
79.0      69
70.0      69
72.0      68
84.0      68
56.0      67
47.0      66
86.0      65
51.0      64
94.0      64
95.0      63
89.0      63
111.0     63
59.0      63
77.0      62
96.0      62
113.0     60
106.0     60
100.0     60
102.0     59
41.0      59
91.0      58
85.0      58
101.0     58
97.0      57
38.0      57
88.0      56
35.0      55
37.0      55
31.0      54
46.0      54
40.0      53
36.0      53
117.0     51
99.0      51
108.0     51
103.0     51
93.0      50
107.0     50
118.0     50
32.0      50
33.0   

In [65]:
df['rec'].isna().sum()

np.int64(14)

In [66]:
df['rec'].unique()

array([183., 175., 164., 179., 347., 190., 189., 167., 104., 217., 309.,
       266., 160., 150., 180., 195., 145., 169., 254., 225., 135., 136.,
       200., 115., 283., 218., 186., 256., 144., 151., 128., 157., 113.,
       198., 203.,  93., 100., 243., 182., 127., 185., 178., 208., 220.,
       201., 197., 215., 122., 227., 174., 142., 155., 134., 202., 141.,
       137., 239.,  90., 109., 168., 132.,  81., 162., 125., 107., 247.,
       154., 214., 172., 111., 103.,  94., 240., 176., 161., 177., 163.,
       147., 173., 181., 272., 308., 171., 213., 140., 166., 110., 199.,
       118., 153.,  86., 235., 170., 230., 149., 101.,  96.,  76., 129.,
       188., 126., 156., 304., 184., 119., 152., 105., 117.,  95.,  87.,
       234.,  92., 165., 139., 124., 238.,  67., 120., 116., 112., 114.,
        80., 133.,  83., 102., 108., 121., 106., 146., 148.,  99., 187.,
       246., 221., 159., 205., 294.,  98.,  77., 143.,  89.,  88., 224.,
       138., 210., 261., 231., 123.,  75.,  91., 20

In [67]:
df['rec'].value_counts()

rec
0.0      762
81.0     107
68.0     103
76.0     100
75.0      98
84.0      96
72.0      96
60.0      96
73.0      95
89.0      95
70.0      95
78.0      89
67.0      88
59.0      87
54.0      87
74.0      86
77.0      85
63.0      85
85.0      85
65.0      84
64.0      84
80.0      83
61.0      83
79.0      83
69.0      83
66.0      79
102.0     79
93.0      78
91.0      78
83.0      77
53.0      77
98.0      77
86.0      76
71.0      76
48.0      75
50.0      74
57.0      74
87.0      74
58.0      73
62.0      73
96.0      72
55.0      72
90.0      71
88.0      70
82.0      69
94.0      68
44.0      68
100.0     67
101.0     67
52.0      66
56.0      65
105.0     65
92.0      64
43.0      64
99.0      64
47.0      62
45.0      61
103.0     60
49.0      60
42.0      60
46.0      57
51.0      57
106.0     57
95.0      55
36.0      55
116.0     55
104.0     54
39.0      54
97.0      53
107.0     53
117.0     52
108.0     52
115.0     51
110.0     49
112.0     49
118.0     49
120.0   

In [68]:
df['points_allowed'].isna().sum()

np.int64(0)

In [69]:
df['points_allowed'].value_counts()

points_allowed
0     934
24    433
17    382
31    372
14    367
21    338
20    322
27    320
10    307
7     287
38    285
28    278
34    276
13    246
35    232
41    194
45    187
30    183
23    182
42    178
3     165
37    134
16    125
49    105
26    103
52    100
33     99
6      96
19     92
48     91
44     84
29     83
40     70
22     69
32     55
25     55
9      54
56     52
15     51
12     48
39     47
36     46
55     44
18     42
43     40
59     38
51     34
47     32
50     25
63     24
46     19
11     18
62     14
53     13
54     13
66     13
58     12
70      7
8       6
69      4
61      4
77      3
73      3
57      2
71      2
65      2
5       2
60      2
2       2
64      1
Name: count, dtype: int64

In [70]:
df['points_allowed'].unique()

array([34, 50, 38, 49, 45, 35, 59, 53, 55, 52, 29, 23, 77, 43, 39, 31, 42,
       37, 27, 48, 33, 20, 21, 70, 28,  7, 17, 24, 30, 25, 46, 40, 56,  6,
       26, 44, 19, 36, 51, 11, 41, 47,  0,  3, 10, 32, 58, 14, 16, 13,  9,
       22, 15, 18, 66, 63, 54, 62, 57, 61, 12, 69,  8, 65, 71,  5, 60, 64,
        2, 73])

In [71]:
df['points_scored'].isna().sum()

np.int64(0)

In [72]:
df['points_scored'].unique()

array([44, 49, 45, 41, 48, 42, 39, 59, 53, 40, 47, 46, 63, 32, 34, 35, 24,
       33, 31, 30, 38, 50, 36, 51, 26, 43, 28, 52, 70, 29, 37, 21, 56, 27,
       23, 20, 55, 54, 61, 66, 76, 17, 58, 73, 77, 69, 25, 14, 13, 18, 22,
       12, 19, 10, 62, 15, 65, 16, 11, 64,  6,  9,  7, 81, 57, 68, 60, 72,
       87,  3, 71,  2,  0,  8, 78,  5])

In [ ]:
df['points_scored'].value_counts()

In [74]:
df['point_differential'].isna().sum()

np.int64(0)

In [75]:
df['point_differential'].unique()

array([ 10,  -1,   7,  -8,   3, -20,   6,  -2,  11,  -5,  36,  -3, -14,
        -6, -11,  -4,  32,  17,  21,  -7, -17,   1, -10,  18,  23,  16,
        34, -15,  35,   8, -12,  20,  28,   2, -16,  14,  38,  26, -28,
        37,  13,  24, -21,   5, -13,  33,  52,  25,  39,  12,  49,  29,
        56,   4, -27,  22,  19,  40,  76,  31,  15,   9,  42,  66,  70,
       -18,  -9, -24,  41,  45,  27,  44,  73,  53,  46,  57, -32,  59,
        30, -23, -46,  48, -22, -31, -19,  62, -26, -29,  43,  55, -25,
       -35, -38, -33,  47, -39, -45,  58,  51,  69, -40,  74, -36, -30,
        50, -49, -34, -37,  77,  65, -44, -42, -57, -51,  68,  60, -41,
       -47, -56, -53,  63, -52,  54,  71, -58, -43, -73, -48, -50, -60,
       -59, -62, -55, -63, -66, -71,   0])

In [76]:
df['point_differential'].value_counts()

point_differential
 0     762
 3     400
-3     384
 7     323
-7     317
 10    180
 14    174
-10    171
-14    168
 17    161
 21    159
-17    152
 4     139
-21    136
-4     135
-2     130
 2     129
-6     127
 6     124
 28    122
 1     121
 8     118
-1     118
-8     113
 24    107
-28    104
-24    102
 11     94
 18     91
 5      91
-5      87
-11     87
 31     86
-18     81
-13     77
 35     76
 13     75
 20     73
-31     71
-20     68
 15     66
 27     64
-15     64
 25     63
 32     60
-27     60
-35     59
 12     59
 34     57
-25     57
-12     56
 23     55
 38     52
 42     51
-9      49
 22     48
-32     48
 9      47
 16     46
-19     46
 19     46
-23     45
-22     44
-34     44
-16     43
 26     43
 29     41
-38     41
 45     39
-26     38
-29     37
-42     35
 33     32
 37     32
 49     32
-33     29
 52     28
 30     28
 41     28
 39     27
-45     26
 56     25
-30     24
-37     23
-49     21
 40     20
 46     20
-39     19
-41     18
 3

In [77]:
df['home_game'].isna().sum()

np.int64(0)

In [78]:
df['home_game'].unique()

array(['FALSE', 'TRUE', 'Bye'], dtype=object)

In [79]:
df['home_game'].value_counts()

home_game
TRUE     4420
FALSE    3366
Bye       762
Name: count, dtype: int64

In [80]:
df['week'].isna().sum()

np.int64(0)

In [81]:
df['week'].unique()

array([-7, -1,  7, 14, 12,  3,  2,  4, 10,  9, 13,  6,  1, 11, 15,  5, -3,
        8,  0, -2, -5, -4, -6, 16, -8, 17, 18, -9])

In [83]:
df['week'].value_counts().sort_index()

week
-9       1
-8       8
-7      20
-6      37
-5      56
-4      68
-3      73
-2      85
-1      93
 0     105
 1     641
 2     645
 3     650
 4     650
 5     650
 6     650
 7     525
 8     525
 9     525
 10    525
 11    524
 12    523
 13    492
 14    333
 15    115
 16     19
 17      6
 18      4
Name: count, dtype: int64

In [84]:
df['season'].isna().sum()

np.int64(0)

In [85]:
df['season'].unique()

array([2020, 2022, 2021, 2023, 2024])

In [86]:
df['season'].value_counts()

season
2024    1932
2023    1794
2022    1779
2021    1761
2020    1282
Name: count, dtype: int64

In [87]:
df['CONF'].isna().sum()

np.int64(0)

In [88]:
df['CONF'].unique()

array(['SEC', 'American', 'Sun Belt', 'CUSA', 'Big Ten', 'ACC', 'Big 12',
       'MAC', 'Pac-12', 'Mountain West', 'FBS Indep.'], dtype=object)

In [89]:
df['CONF'].value_counts()

CONF
SEC              1007
ACC              1003
Big Ten           974
Big 12            824
American          808
Sun Belt          790
Mountain West     769
CUSA              739
MAC               694
Pac-12            593
FBS Indep.        347
Name: count, dtype: int64

In [90]:
df['SOR'].isna().sum()

np.int64(0)

In [91]:
df['SOR'].unique()

array([ 70,  56,  97,  61,   8,   2,  52,  34,  48,  60,  18,  16, 117,
       115,  54,  21,   9,  13,  42,  77,  10,  73,  79,  38,  95,  69,
       113,  65,  86,  17, 124,  26,  11, 107,  51,  23, 130,  62,   1,
        67,  82, 106,  64,  94, 112,  89,   4,  15,  20, 126,  30,  29,
        44,  71,  24,  55, 100,  74,  28, 108,  43,  93,  39, 125, 118,
         6,  22,  84, 104,  36, 116,  85,  78,  96,  92, 110,  66,  40,
        50,  19,  35,  14,  90,  32, 119, 123,  88, 102,  45,  41,  72,
        87, 120,  47,  58, 121,  27, 114,  37,   7,  63, 101,  99,  33,
       111, 134,  49,  91,   3,   5,  76, 128,  68,  12,  81,  80,  25,
        46, 105,  83,  98,  31,  57, 103, 122, 127, 109,  75, 129,  53,
        59, 132, 131, 133])

In [92]:
df['SOR'].value_counts()

SOR
119    120
1       81
6       76
3       76
5       75
2       74
4       74
14      74
15      73
38      73
8       73
16      72
20      72
27      72
87      71
12      71
49      71
70      71
17      71
21      71
43      71
10      71
34      71
36      70
7       70
30      70
63      70
105     69
61      69
19      69
42      69
28      69
32      68
46      68
18      68
54      68
55      68
72      68
103     68
33      68
58      68
56      67
40      67
44      67
106     67
23      67
26      67
91      67
90      67
110     67
9       67
66      67
97      66
31      66
94      66
85      66
75      66
116     66
37      66
102     66
92      66
114     66
48      66
24      66
93      66
71      66
62      66
13      66
11      65
60      65
86      65
76      65
25      64
83      64
109     64
89      64
59      64
45      64
74      64
79      64
52      64
22      63
108     63
81      63
41      63
118     63
51      63
95      63
115     63
112     63
100   

In [93]:
df['FPI'].isna().sum()

np.int64(0)

In [94]:
df['FPI'].unique()

array([ 52,  22,  91,  41,   3,   2,  47,  26,  58,  90,  25,  93,  20,
       111,  97,  53,  54,  12,   5,  35,  77,   6,  62,  48,  69,  85,
        16,  60,  95,  73, 109,  59,  64,  11,  67, 129,  49, 115,  61,
        71, 126,   1,  34,  80, 112,  68,  65, 110,  84,   7,  44,  19,
       128,  57,  33,  51,  15,  28,  23,  18,  43, 117,  32,  36, 118,
        30,  98,  75,  99,  70,  88, 101,  14,  76, 123,  13, 127,  50,
       107, 116,   9,  72,  92,  63,   8,  78, 131,  10,   4,  37,  94,
       108, 100,  38, 102,  81,  39,  17,  42, 105, 121, 106, 122, 124,
       134,  89,  31,  45,  24,  74,  83, 113, 103,  55,  82, 120,  56,
        79,  87,  40, 119,  21,  66,  96,  86,  29, 114,  27, 104, 130,
       133,  46, 125, 132])

In [95]:
df['AP/CFP'].isna().sum()

np.int64(0)

In [96]:
df['AP/CFP'].unique()

array(['--', '6', '1', '13', '14', '12', '5', '11', '7', '2', '21', '10',
       '22', '18', '17', '25', '3', '23', '19', '15', '20', '16', '8',
       '9', '24', '4'], dtype=object)

In [97]:
df['SOS'].isna().sum()

np.int64(0)

In [98]:
df['SOS'].unique()

array([  4,  68, 118,  92,  27,   1,  49,  42,  31,  86,  15,  73,  57,
        98, 104,  80,  60,  37,  17,  39,  43,  65, 107,  67,  89,  25,
        41,  70, 125,  47,  78,  97,  90,  83, 115,  75,  35,  88,   6,
       130,  28, 108,  93,  87,  63,  45, 116,   7,  95,   9, 111,   3,
        12,  46,   5,  32, 103, 122,  36, 128,  34, 119,  48, 121,  71,
        20,  13,  56,  10,  30,  76, 113, 123, 100,  23,  53,  61,  33,
        84,  74,  69,  55, 101,  94,  50,   8,  58, 109,  21,  29,  79,
        24,  96,  77, 129,  52, 114,  14,  85,  38,  99, 102,  91,  66,
        40,  26,  11, 120,  18,  16, 117,  59, 105,  82,  62,  19, 110,
       124,  44,  72, 112,  22,  81,   2, 126,  51, 106, 127, 131,  64,
        54, 132, 133, 134])

In [99]:
df['GC'].isna().sum()

np.int64(0)

In [100]:
df['GC'].unique()

array([ 61,  18, 109,  64,   4,   2,  50,  25,  56,  74,  91,  23, 105,
       107,  70,  62,  13,  14,   3,  37,  80,   9,  81,  90,  87,  15,
        92,  94,  73, 111,  69,  59, 122,  46,   6, 106,  53,  67, 118,
        68,   1,  45,  76, 112,  66,  78, 102,  12,  26,  11,  35,  16,
        58, 124,  28,  41,  10,  21, 101,  96,  20, 117,  43,  44,  38,
        33,  34,  32,  65,  51,  93,  77,  75,  36,  52,  17,  47, 119,
        57,  54, 120,  27,  19,   5, 115,   8, 108, 104,  84,  30,  85,
        48,  49,  42, 100, 110, 114,  39,  86,  63,  97,  95,  72,  98,
        31,  60,  29,   7,  89,  83,  82,  24,  71, 116,  55, 113,  40,
        88, 121,  79,  22,  99, 103, 123])

In [101]:
df['AVGWP'].isna().sum()

np.int64(0)

In [102]:
df['AVGWP'].unique()

array([ 90,  12,  43,   8,   3,  68,  25,  91,  42,  47,  78,  30, 102,
       106,  77,  62,   9,   2,  59, 115,  11,  97,  32,  99,  67,  31,
        94,  61,  54,  98,  51,  75,  28,  35, 127,  38,   7,  84,  22,
        29, 124,  57,   1,  50,  87,  96,  46,  13,  55, 130,  19,   4,
        81,   5,  60,  26,  72,  69,  70,  52, 126, 108,  73,   6,  74,
       112,  33,  34,  56,  71,  41,  89,  49,  58,  79,  45, 122,  23,
       117, 123, 109, 110, 116,  18,  15,  63,  10, 125,  37,  83,  85,
       100,  66,  53,  20,  80,  48,  82,  40, 103,  27,  95, 121, 128,
       101, 134,  39,  17,  86, 119,  16,  36,  44,  65, 111, 129,  14,
        64,  93, 118,  92,  21,  76, 104, 114,  88,  24, 107, 133, 131,
       120, 105, 132, 113])