In [101]:
import pandas as pd
import numpy as np
# cpd.reset_option('display.max_rows')
# pd.set_option('display.max_rows', None)

In [102]:
df = pd.read_csv('WeekByWeekRankings2020to2025.csv')
df
df_copy = df.copy()

In [103]:
df1 = pd.read_csv('CollegeFootballRankings24to20.csv')
df1
df_copy = df.copy()

In [104]:
df

AP_rank            Team  Week  year
0           1         Georgia     1  2024
1           2      Ohio State     1  2024
2           3          Oregon     1  2024
3           4           Texas     1  2024
4           5         Alabama     1  2024
...       ...             ...   ...   ...
1970       21             USC    16  2020
1971       22           Miami    16  2020
1972       23      Ball State    16  2020
1973       24  San José State    16  2020
1974       25         Buffalo    16  2020

[1975 rows x 4 columns]

In [105]:
df['AP_rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [106]:
df['AP_rank'].value_counts()

AP_rank
8     81
11    81
3     80
16    80
2     80
21    80
7     79
1     79
5     79
23    79
24    79
6     79
13    79
15    79
14    79
18    79
10    79
25    79
20    79
19    79
17    78
22    78
4     77
9     77
12    77
Name: count, dtype: int64

In [107]:
df['AP_rank'].isna().sum()

np.int64(0)

In [108]:
df['Team'].isna().sum()

np.int64(0)

In [109]:
df['Team'].unique()

array(['Georgia', 'Ohio State', 'Oregon', 'Texas', 'Alabama', 'Ole Miss',
       'Notre Dame', 'Michigan', 'Penn State', 'Florida State',
       'Missouri', 'LSU', 'Utah', 'Clemson', 'Tennessee', 'Oklahoma',
       'Kansas State', 'Oklahoma State', 'Miami', 'Texas A&M', 'Arizona',
       'NC State', 'USC', 'Kansas', 'Iowa', 'Louisville', 'Washington',
       'Iowa State', 'Nebraska', 'Memphis', 'UNLV', 'Illinois', 'BYU',
       'Indiana', 'Boise State', 'Pittsburgh', 'SMU', 'Army', 'Navy',
       'Vanderbilt', 'Washington State', 'Colorado', 'South Carolina',
       'Tulane', 'Arizona State', 'Syracuse', 'TCU', 'Oregon State',
       'North Carolina', 'Wisconsin', 'Texas Tech', 'Duke', 'UCLA',
       'Florida', 'Kentucky', 'Fresno State', 'Air Force',
       'James Madison', 'Liberty', 'Toledo', 'West Virginia', 'Baylor',
       'Michigan State', 'Wake Forest', 'Cincinnati', 'Arkansas',
       'Houston', 'Minnesota', 'Mississippi State', 'UCF',
       'Coastal Carolina', 'UTSA', 'Troy'

In [110]:
df['Team'].value_counts()

Team
Georgia              79
Alabama              79
Ohio State           78
Oregon               74
Notre Dame           71
                     ..
West Virginia         1
Utah State            1
Appalachian State     1
Ball State            1
San José State        1
Name: count, Length: 85, dtype: int64

In [111]:
df['Week'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [112]:
df['Week'].isna().sum()

np.int64(0)

In [113]:
df['Week'].value_counts()

Week
1     125
3     125
4     125
5     125
7     125
6     125
8     125
9     125
13    125
10    125
11    125
12    125
15    125
14    125
16    125
2     100
Name: count, dtype: int64

In [114]:
df['year'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [115]:
df['year'].value_counts()

year
2024    400
2023    400
2022    400
2021    400
2020    375
Name: count, dtype: int64

In [116]:
df['year'].isna().sum()

np.int64(0)

In [117]:
df1

Team         date         opponent win_loss pass rush  rec  \
0     Air Force Falcons  Sat, Aug 31        Merrimack        W   71   63   21   
1     Air Force Falcons   Sat, Nov 9     Fresno State        W   14  120   11   
2     Air Force Falcons  Sat, Nov 30  San Diego State        W   76  125   76   
3     Air Force Falcons  Sat, Sep 14           Baylor        L   18   71   18   
4     Air Force Falcons  Sat, Sep 28          Wyoming        L  115   54  106   
...                 ...          ...              ...      ...  ...  ...  ...   
7052    Wyoming Cowboys  Fri, Oct 30          Hawai'i        W  112  163   32   
7053    Wyoming Cowboys  Fri, Nov 27             UNLV        W   99  164   42   
7054    Wyoming Cowboys   Sat, Dec 5      New Mexico         L   73  154   54   
7055    Wyoming Cowboys  Sat, Oct 24           Nevada        L  227   87  102   
7056    Wyoming Cowboys  Sat, Dec 12      Boise State        L   45   59   29   

      points_allowed  points_scored  point_differential  home_game  season  \
0                  6             21                  15       True    2024   
1                 28             36                   8       True    2024   
2                 20             31                  11      False    2024   
3                 31              3                 -28      False    2024   
4                 31             19                 -12      False    2024   
...              ...            ...                 ...        ...     ...   
7052               7             31                  24       True    2020   
7053              14             45                  31      False    2020   
7054              17             16                  -1       True    2020   
7055              37             34                  -3      False    2020   
7056              17              9                  -8       True    2020   

               CONF  SOR  FPI AP/CFP  SOS   GC  AVGWP  
0     Mountain West  108  106     --  117  115    100  
1     Mountain West  108  106     --  117  115    100  
2     Mountain West  108  106     --  117  115    100  
3     Mountain West  108  106     --  117  115    100  
4     Mountain West  108  106     --  117  115    100  
...             ...  ...  ...    ...  ...  ...    ...  
7052  Mountain West  100   73     --  117   95     74  
7053  Mountain West  100   73     --  117   95     74  
7054  Mountain West  100   73     --  117   95     74  
7055  Mountain West  100   73     --  117   95     74  
7056  Mountain West  100   73     --  117   95     74  

[7057 rows x 19 columns]

In [118]:
df1['Team'].unique()

array(['Air Force Falcons', 'Akron Zips', 'Alabama Crimson Tide',
       'App State Mountaineers', 'Arizona State Sun Devils',
       'Arizona Wildcats', 'Arkansas Razorbacks',
       'Arkansas State Red Wolves', 'Army Black Knights', 'Auburn Tigers',
       'Ball State Cardinals', 'Baylor Bears', 'Boise State Broncos',
       'Boston College Eagles', 'Bowling Green Falcons', 'Buffalo Bulls',
       'BYU Cougars', 'California Golden Bears',
       'Central Michigan Chippewas', 'Charlotte 49ers',
       'Cincinnati Bearcats', 'Clemson Tigers',
       'Coastal Carolina Chanticleers', 'Colorado Buffaloes',
       'Colorado State Rams', 'Duke Blue Devils', 'East Carolina Pirates',
       'Eastern Michigan Eagles', 'Florida Atlantic Owls',
       'Florida Gators', 'Florida International Panthers',
       'Florida State Seminoles', 'Fresno State Bulldogs',
       'Georgia Bulldogs', 'Georgia Southern Eagles',
       'Georgia State Panthers', 'Georgia Tech Yellow Jackets',
       "Hawai'i Rai

In [119]:
df1['Team'].value_counts()

Team
Georgia Bulldogs                65
Alabama Crimson Tide            64
Notre Dame Fighting Irish       63
Iowa State Cyclones             63
Clemson Tigers                  63
                                ..
James Madison Dukes             34
Jacksonville State Gamecocks    18
Sam Houston Bearkats            15
App State Mountaineers           9
Kennesaw State Owls              9
Name: count, Length: 134, dtype: int64

In [120]:
df1['Team'].isna().sum()

np.int64(0)

In [121]:
df1['opponent'].unique()

array(['Merrimack', 'Fresno State', 'San Diego State', 'Baylor',
       'Wyoming', 'Navy', 'San José State', 'Colorado State', ' Army',
       'New Mexico', 'Nevada', 'Oregon State', 'South Carolina',
       ' Ohio State', 'Rutgers', 'Colgate', 'Bowling Green',
       'Western Michigan', 'Eastern Michigan', 'Ohio', 'Buffalo',
       'Oklahoma', 'Auburn', 'Western Kentucky', 'South Florida',
       'Wisconsin', ' Georgia', 'Vanderbilt', ' Tennessee', ' Missouri',
       ' LSU', 'Mercer', 'East Tennessee State', 'Georgia Southern',
       'Louisiana', 'East Carolina', 'Marshall', ' Clemson',
       'Old Dominion', 'James Madison', 'Georgia State', ' Utah',
       'Arizona', 'UCF', ' Kansas State', ' BYU', 'Mississippi State',
       'Texas Tech', 'Kansas', 'Cincinnati', 'Oklahoma State',
       ' Iowa State ', 'Colorado', 'Northern Arizona', 'Houston', 'TCU',
       'West Virginia', ' Arizona State', ' Ole Miss', 'Louisiana Tech',
       'Texas Tech ', ' Oklahoma State', 'UAB', ' Texas A

In [122]:
df1['opponent'].value_counts()

opponent
Vanderbilt           54
Hawai'i              53
 Alabama             52
Rutgers              52
UTSA                 52
                     ..
Yale                  1
Oregon State          1
Montana               1
Central Michigan      1
 Memphis              1
Name: count, Length: 481, dtype: int64