In [124]:
import pandas as pd
import numpy as np
# pd.reset_option('display.max_rows')
pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_csv('WeekByWeekRankings2020to2025.csv')
df_copy = df.copy()

In [ ]:
df1 = pd.read_csv('CollegeFootballRankings24to20.csv')
df_copy = df.copy()

In [123]:
headers = df.columns
print(headers)

Index(['AP_rank', 'Team', 'Week', 'year'], dtype='object')


In [105]:
df['AP_rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [125]:
df['AP_rank'].value_counts()

AP_rank
8     81
11    81
3     80
16    80
2     80
21    80
7     79
1     79
5     79
23    79
24    79
6     79
13    79
15    79
14    79
18    79
10    79
25    79
20    79
19    79
17    78
22    78
4     77
9     77
12    77
Name: count, dtype: int64

In [107]:
df['AP_rank'].isna().sum()

np.int64(0)

In [108]:
df['Team'].isna().sum()

np.int64(0)

In [109]:
df['Team'].unique()

array(['Georgia', 'Ohio State', 'Oregon', 'Texas', 'Alabama', 'Ole Miss',
       'Notre Dame', 'Michigan', 'Penn State', 'Florida State',
       'Missouri', 'LSU', 'Utah', 'Clemson', 'Tennessee', 'Oklahoma',
       'Kansas State', 'Oklahoma State', 'Miami', 'Texas A&M', 'Arizona',
       'NC State', 'USC', 'Kansas', 'Iowa', 'Louisville', 'Washington',
       'Iowa State', 'Nebraska', 'Memphis', 'UNLV', 'Illinois', 'BYU',
       'Indiana', 'Boise State', 'Pittsburgh', 'SMU', 'Army', 'Navy',
       'Vanderbilt', 'Washington State', 'Colorado', 'South Carolina',
       'Tulane', 'Arizona State', 'Syracuse', 'TCU', 'Oregon State',
       'North Carolina', 'Wisconsin', 'Texas Tech', 'Duke', 'UCLA',
       'Florida', 'Kentucky', 'Fresno State', 'Air Force',
       'James Madison', 'Liberty', 'Toledo', 'West Virginia', 'Baylor',
       'Michigan State', 'Wake Forest', 'Cincinnati', 'Arkansas',
       'Houston', 'Minnesota', 'Mississippi State', 'UCF',
       'Coastal Carolina', 'UTSA', 'Troy'

In [143]:
df['Team'].value_counts()
dfteam_values = df['Team'].value_counts()
dfteam_sorted_values = dfteam_values.sort_index(ascending = True)
print(dfteam_sorted_values)

Team
Air Force             3
Alabama              79
Appalachian State     1
Arizona               9
Arizona State         8
Arkansas             16
Army                 13
Auburn               18
BYU                  43
Ball State            1
Baylor               18
Boise State          11
Buffalo               2
Cincinnati           37
Clemson              63
Coastal Carolina     22
Colorado             10
Duke                  8
Florida              26
Florida State        24
Fresno State          5
Georgia              79
Houston               8
Illinois             14
Indiana              20
Iowa                 29
Iowa State           30
James Madison         7
Kansas                9
Kansas State         34
Kentucky             21
LSU                  42
Liberty              12
Louisiana            17
Louisville           19
Marshall              7
Memphis               8
Miami                40
Michigan             62
Michigan State       17
Minnesota             5
Mississippi

In [111]:
df['Week'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [112]:
df['Week'].isna().sum()

np.int64(0)

In [128]:
df['Week'].value_counts()

Week
1     125
3     125
4     125
5     125
7     125
6     125
8     125
9     125
13    125
10    125
11    125
12    125
15    125
14    125
16    125
2     100
Name: count, dtype: int64

In [114]:
df['year'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [115]:
df['year'].value_counts()

year
2024    400
2023    400
2022    400
2021    400
2020    375
Name: count, dtype: int64

In [116]:
df['year'].isna().sum()

np.int64(0)

In [129]:
headers1 = df1.columns
print(headers1)

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')


In [118]:
df1['Team'].unique()

array(['Air Force Falcons', 'Akron Zips', 'Alabama Crimson Tide',
       'App State Mountaineers', 'Arizona State Sun Devils',
       'Arizona Wildcats', 'Arkansas Razorbacks',
       'Arkansas State Red Wolves', 'Army Black Knights', 'Auburn Tigers',
       'Ball State Cardinals', 'Baylor Bears', 'Boise State Broncos',
       'Boston College Eagles', 'Bowling Green Falcons', 'Buffalo Bulls',
       'BYU Cougars', 'California Golden Bears',
       'Central Michigan Chippewas', 'Charlotte 49ers',
       'Cincinnati Bearcats', 'Clemson Tigers',
       'Coastal Carolina Chanticleers', 'Colorado Buffaloes',
       'Colorado State Rams', 'Duke Blue Devils', 'East Carolina Pirates',
       'Eastern Michigan Eagles', 'Florida Atlantic Owls',
       'Florida Gators', 'Florida International Panthers',
       'Florida State Seminoles', 'Fresno State Bulldogs',
       'Georgia Bulldogs', 'Georgia Southern Eagles',
       'Georgia State Panthers', 'Georgia Tech Yellow Jackets',
       "Hawai'i Rai

In [142]:
df1['Team'].value_counts()
team_values = df1['Team'].value_counts()
team_sorted_values = team_values.sort_index(ascending = True)
print(team_sorted_values)

Team
Air Force Falcons                 54
Akron Zips                        41
Alabama Crimson Tide              64
App State Mountaineers             9
Arizona State Sun Devils          49
Arizona Wildcats                  53
Arkansas Razorbacks               59
Arkansas State Red Wolves         56
Army Black Knights                60
Auburn Tigers                     60
BYU Cougars                       60
Ball State Cardinals              39
Baylor Bears                      58
Boise State Broncos               58
Boston College Eagles             57
Bowling Green Falcons             36
Buffalo Bulls                     39
California Golden Bears           52
Central Michigan Chippewas        38
Charlotte 49ers                   51
Cincinnati Bearcats               61
Clemson Tigers                    63
Coastal Carolina Chanticleers     50
Colorado Buffaloes                53
Colorado State Rams               50
Duke Blue Devils                  57
East Carolina Pirates            

In [120]:
df1['Team'].isna().sum()

np.int64(0)

In [131]:
df1['date'].isna().sum()

np.int64(0)

In [132]:
df1['date'].unique()

array(['Sat, Aug 31', 'Sat, Nov 9', 'Sat, Nov 30', 'Sat, Sep 14',
       'Sat, Sep 28', 'Sat, Oct 5', 'Sat, Sep 7', 'Sat, Oct 19',
       'Sat, Nov 2', 'Sat, Oct 12', 'Sat, Nov 23', 'Sat, Nov 16',
       'Sat, Sep 21', 'Sat, Oct 26', 'Fri, Oct 11', 'Sat, Dec 7',
       'Fri, Sep 13', 'Fri, Nov 15', 'Fri, Dec 27', 'Fri, Aug 30',
       'Sat, Dec 14', 'Fri, Dec 6', 'Sat, Dec 28', 'Fri, Nov 29',
       'Fri, Oct 25', 'Fri, Nov 1', 'Sat, Jan 4', 'Fri, Sep 6',
       'Fri, Oct 18', 'Fri, Nov 8', 'Sat, Dec 21', 'Fri, Dec 20',
       'Sat, Aug 24', 'Fri, Oct 4', 'Fri, Sep 20', 'Fri, Sep 27',
       'Fri, Nov 22', 'Fri, Jan 3', 'Fri, Jan 10', 'Sat, Oct 21',
       'Sat, Sep 9', 'Sat, Nov 18', 'Sat, Oct 28', 'Sat, Nov 4',
       'Sat, Sep 2', 'Fri, Sep 15', 'Fri, Nov 24', 'Sat, Dec 23',
       'Sat, Nov 11', 'Fri, Sep 22', 'Sat, Sep 30', 'Sat, Oct 14',
       'Sat, Sep 16', 'Sat, Oct 7', 'Sat, Sep 23', 'Sat, Nov 25',
       'Sat, Dec 2', 'Sat, Dec 9', 'Sat, Dec 30', 'Sat, Dec 16',
       'Fri, 

In [141]:
df1['date'].value_counts()
date_values = df1['date'].value_counts()
date_sorted_values = date_values.sort_index(ascending = True)
print(date_sorted_values)

date
Fri, Aug 30     10
Fri, Dec 1       4
Fri, Dec 11      6
Fri, Dec 16      4
Fri, Dec 17      4
Fri, Dec 18      8
Fri, Dec 2       6
Fri, Dec 20      6
Fri, Dec 22      2
Fri, Dec 23      5
Fri, Dec 25      2
Fri, Dec 27     10
Fri, Dec 29      8
Fri, Dec 3       4
Fri, Dec 30      9
Fri, Dec 31      9
Fri, Dec 4       1
Fri, Dec 6       6
Fri, Jan 1       8
Fri, Jan 10      2
Fri, Jan 3       4
Fri, Nov 1       6
Fri, Nov 10      4
Fri, Nov 11      6
Fri, Nov 12      4
Fri, Nov 13      6
Fri, Nov 15      8
Fri, Nov 17      4
Fri, Nov 18      4
Fri, Nov 19     10
Fri, Nov 20      8
Fri, Nov 22      6
Fri, Nov 24     26
Fri, Nov 25     25
Fri, Nov 26     31
Fri, Nov 27     18
Fri, Nov 29     28
Fri, Nov 3       4
Fri, Nov 4       6
Fri, Nov 5       4
Fri, Nov 6       5
Fri, Nov 8       9
Fri, Oct 1       6
Fri, Oct 11      6
Fri, Oct 13      6
Fri, Oct 14      4
Fri, Oct 15      8
Fri, Oct 16      4
Fri, Oct 18      8
Fri, Oct 2       4
Fri, Oct 20      2
Fri, Oct 21      4
Fri, Oc

In [121]:
df1['opponent'].unique()

array(['Merrimack', 'Fresno State', 'San Diego State', 'Baylor',
       'Wyoming', 'Navy', 'San José State', 'Colorado State', ' Army',
       'New Mexico', 'Nevada', 'Oregon State', 'South Carolina',
       ' Ohio State', 'Rutgers', 'Colgate', 'Bowling Green',
       'Western Michigan', 'Eastern Michigan', 'Ohio', 'Buffalo',
       'Oklahoma', 'Auburn', 'Western Kentucky', 'South Florida',
       'Wisconsin', ' Georgia', 'Vanderbilt', ' Tennessee', ' Missouri',
       ' LSU', 'Mercer', 'East Tennessee State', 'Georgia Southern',
       'Louisiana', 'East Carolina', 'Marshall', ' Clemson',
       'Old Dominion', 'James Madison', 'Georgia State', ' Utah',
       'Arizona', 'UCF', ' Kansas State', ' BYU', 'Mississippi State',
       'Texas Tech', 'Kansas', 'Cincinnati', 'Oklahoma State',
       ' Iowa State ', 'Colorado', 'Northern Arizona', 'Houston', 'TCU',
       'West Virginia', ' Arizona State', ' Ole Miss', 'Louisiana Tech',
       'Texas Tech ', ' Oklahoma State', 'UAB', ' Texas A

In [140]:
df1['opponent'].value_counts()
opponent_values = df1['opponent'].value_counts()
opponent_sorted_values = values.sort_index(ascending = True)
print(opponent_sorted_values)

opponent
 Air Force                   2
 Air Force                   1
 Alabama                    52
 Alabama                     7
 Appalachian State           1
 Arizona                     5
 Arizona State               5
 Arizona State               1
 Arkansas                    9
 Arkansas                    3
 Army                        5
 Army                        3
 Auburn                     10
 BYU                        27
 BYU                         2
 Baylor                     10
 Baylor                      2
 Boise State                12
 Boston College              1
 Cincinnati                 20
 Cincinnati                  2
 Clemson                    31
 Clemson                     8
 Coastal Carolina            9
 Coastal Carolina            1
 Colorado                    8
 Colorado                    1
 Duke                        5
 Florida                    19
 Florida                     2
 Florida State              16
 Florida State               3

In [137]:
df1['opponent'].value_counts()

opponent
Vanderbilt                  54
Hawai'i                     53
 Alabama                    52
Rutgers                     52
UTSA                        52
UL Monroe                   51
Boston College              51
North Texas                 51
 Ohio State                 51
UAB                         50
Maryland                    50
Nebraska                    50
Stanford                    50
Texas Tech                  50
Texas State                 50
South Carolina              50
Nevada                      50
Arkansas State              49
Syracuse                    49
Florida Atlantic            49
South Florida               49
Temple                      49
Virginia                    48
Purdue                      48
West Virginia               48
Western Kentucky            48
Wyoming                     47
Troy                        47
California                  47
Mississippi State           47
Houston                     47
Utah State                  47