In [8]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('WeekByWeekRankings2020to2025.csv')
df

AP_rank            Team  Week  year
0           1         Georgia     1  2024
1           2      Ohio State     1  2024
2           3          Oregon     1  2024
3           4           Texas     1  2024
4           5         Alabama     1  2024
...       ...             ...   ...   ...
1970       21             USC    16  2020
1971       22           Miami    16  2020
1972       23      Ball State    16  2020
1973       24  San José State    16  2020
1974       25         Buffalo    16  2020

[1975 rows x 4 columns]

In [3]:
df['AP_rank'].isna().sum()

np.int64(0)

In [4]:
df['AP_rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
df['Team'].isna().sum()

np.int64(0)

In [ ]:
unique_team = df['Team'].unique()
unique_team = sorted(unique_team)
unique_team

In [9]:
df['Team'].value_counts()

Team
Georgia              79
Alabama              79
Ohio State           78
Oregon               74
Notre Dame           71
Penn State           64
Clemson              63
Michigan             62
Ole Miss             61
Texas                56
Oklahoma             56
Oklahoma State       52
Tennessee            50
Texas A&M            49
USC                  45
BYU                  43
Utah                 42
LSU                  42
Miami                40
Cincinnati           37
North Carolina       36
Kansas State         34
Iowa State           30
Washington           29
Iowa                 29
NC State             28
Florida              26
Missouri             26
Florida State        24
Wisconsin            24
SMU                  24
Coastal Carolina     22
Tulane               22
Wake Forest          22
Kentucky             21
UCLA                 21
Oregon State         21
Indiana              20
Pittsburgh           19
Louisville           19
Baylor               18
Auburn     

In [11]:
df['Week'].isna().sum()

np.int64(0)

In [12]:
df['Week'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [14]:
df['Week'].value_counts().sort_index()

Week
1     125
2     100
3     125
4     125
5     125
6     125
7     125
8     125
9     125
10    125
11    125
12    125
13    125
14    125
15    125
16    125
Name: count, dtype: int64

In [15]:
df['year'].isna().sum()

np.int64(0)

In [16]:
df['year'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [17]:
df['year'].value_counts()

year
2024    400
2023    400
2022    400
2021    400
2020    375
Name: count, dtype: int64