In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
# pd.reset_option('all')

In [3]:
df = pd.read_csv('CollegeFootballRankings24to20.csv')
# df

In [4]:
for i in df:
    print(i)

Team
date
Team_id
opponent
win_loss
OT
OT_num
pass
rush
rec
points_allowed
points_scored
point_differential
home_game
week
season
CONF
SOR
FPI
AP/CFP
SOS
GC
AVGWP


In [5]:
df['Team'].unique()
team_unique = df['Team'].unique()
team_unique = sorted(team_unique)
team_unique

['Air Force Falcons',
 'Akron Zips',
 'Alabama Crimson Tide',
 'App State Mountaineers',
 'Arizona State Sun Devils',
 'Arizona Wildcats',
 'Arkansas Razorbacks',
 'Arkansas State Red Wolves',
 'Army Black Knights',
 'Auburn Tigers',
 'BYU Cougars',
 'Ball State Cardinals',
 'Baylor Bears',
 'Boise State Broncos',
 'Boston College Eagles',
 'Bowling Green Falcons',
 'Buffalo Bulls',
 'California Golden Bears',
 'Central Michigan Chippewas',
 'Charlotte 49ers',
 'Cincinnati Bearcats',
 'Clemson Tigers',
 'Coastal Carolina Chanticleers',
 'Colorado Buffaloes',
 'Colorado State Rams',
 'Duke Blue Devils',
 'East Carolina Pirates',
 'Eastern Michigan Eagles',
 'Florida Atlantic Owls',
 'Florida Gators',
 'Florida International Panthers',
 'Florida State Seminoles',
 'Fresno State Bulldogs',
 'Georgia Bulldogs',
 'Georgia Southern Eagles',
 'Georgia State Panthers',
 'Georgia Tech Yellow Jackets',
 "Hawai'i Rainbow Warriors",
 'Houston Cougars',
 'Illinois Fighting Illini',
 'Indiana Hoosie

In [6]:
df['Team'].value_counts().sort_index()

Team
Air Force Falcons                 65
Akron Zips                        56
Alabama Crimson Tide              75
App State Mountaineers            14
Arizona State Sun Devils          63
Arizona Wildcats                  58
Arkansas Razorbacks               68
Arkansas State Red Wolves         69
Army Black Knights                74
Auburn Tigers                     68
BYU Cougars                       71
Ball State Cardinals              57
Baylor Bears                      68
Boise State Broncos               67
Boston College Eagles             66
Bowling Green Falcons             57
Buffalo Bulls                     60
California Golden Bears           58
Central Michigan Chippewas        56
Charlotte 49ers                   61
Cincinnati Bearcats               68
Clemson Tigers                    73
Coastal Carolina Chanticleers     70
Colorado Buffaloes                61
Colorado State Rams               57
Duke Blue Devils                  68
East Carolina Pirates            

In [7]:
df['Team'].isna().sum()

np.int64(0)

In [8]:
df['date'].isna().sum()

np.int64(0)

In [9]:
df['date'].nunique()

390

In [10]:
df['date'].value_counts()
date_unique = df['date'].unique()
date_unique = sorted(date_unique)
date_unique

['Fri, Aug 30',
 'Fri, Dec 04',
 'Fri, Dec 1',
 'Fri, Dec 11',
 'Fri, Dec 16',
 'Fri, Dec 17',
 'Fri, Dec 18',
 'Fri, Dec 2',
 'Fri, Dec 20',
 'Fri, Dec 22',
 'Fri, Dec 23',
 'Fri, Dec 25',
 'Fri, Dec 27',
 'Fri, Dec 29',
 'Fri, Dec 3',
 'Fri, Dec 30',
 'Fri, Dec 31',
 'Fri, Dec 4',
 'Fri, Dec 6',
 'Fri, Jan 1',
 'Fri, Jan 10',
 'Fri, Jan 3',
 'Fri, Nov 01',
 'Fri, Nov 04',
 'Fri, Nov 05',
 'Fri, Nov 06',
 'Fri, Nov 1',
 'Fri, Nov 10',
 'Fri, Nov 11',
 'Fri, Nov 12',
 'Fri, Nov 13',
 'Fri, Nov 15',
 'Fri, Nov 17',
 'Fri, Nov 18',
 'Fri, Nov 19',
 'Fri, Nov 20',
 'Fri, Nov 22',
 'Fri, Nov 24',
 'Fri, Nov 25',
 'Fri, Nov 26',
 'Fri, Nov 27',
 'Fri, Nov 29',
 'Fri, Nov 3',
 'Fri, Nov 4',
 'Fri, Nov 5',
 'Fri, Nov 6',
 'Fri, Nov 8',
 'Fri, Oct 06',
 'Fri, Oct 08',
 'Fri, Oct 09',
 'Fri, Oct 1',
 'Fri, Oct 11',
 'Fri, Oct 13',
 'Fri, Oct 14',
 'Fri, Oct 15',
 'Fri, Oct 16',
 'Fri, Oct 18',
 'Fri, Oct 2',
 'Fri, Oct 20',
 'Fri, Oct 21',
 'Fri, Oct 22',
 'Fri, Oct 23',
 'Fri, Oct 25',
 'Fri, 

In [11]:
df['date'].value_counts().sort_index()

date
Fri, Aug 30     10
Fri, Dec 04      2
Fri, Dec 1       4
Fri, Dec 11      6
Fri, Dec 16      4
Fri, Dec 17      4
Fri, Dec 18      8
Fri, Dec 2       6
Fri, Dec 20      6
Fri, Dec 22      2
Fri, Dec 23      5
Fri, Dec 25      3
Fri, Dec 27     10
Fri, Dec 29      8
Fri, Dec 3       4
Fri, Dec 30      9
Fri, Dec 31      9
Fri, Dec 4       1
Fri, Dec 6       6
Fri, Jan 1       8
Fri, Jan 10      2
Fri, Jan 3       4
Fri, Nov 01      3
Fri, Nov 04      1
Fri, Nov 05      1
Fri, Nov 06      2
Fri, Nov 1       6
Fri, Nov 10      4
Fri, Nov 11      6
Fri, Nov 12      4
Fri, Nov 13      7
Fri, Nov 15     10
Fri, Nov 17      4
Fri, Nov 18      4
Fri, Nov 19     10
Fri, Nov 20      8
Fri, Nov 22      6
Fri, Nov 24     26
Fri, Nov 25     25
Fri, Nov 26     31
Fri, Nov 27     20
Fri, Nov 29     28
Fri, Nov 3       4
Fri, Nov 4       6
Fri, Nov 5       4
Fri, Nov 6       5
Fri, Nov 8       9
Fri, Oct 06      3
Fri, Oct 08      1
Fri, Oct 09      2
Fri, Oct 1       6
Fri, Oct 11      9
Fri, Oc

In [12]:
df['Team_id'].isna().sum()

np.int64(0)

In [13]:
team_id_unique = df['Team_id'].unique()
team_id_unique = sorted(team_id_unique)
team_id_unique

[np.int64(2),
 np.int64(5),
 np.int64(6),
 np.int64(8),
 np.int64(9),
 np.int64(12),
 np.int64(21),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(30),
 np.int64(36),
 np.int64(38),
 np.int64(41),
 np.int64(52),
 np.int64(55),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(61),
 np.int64(62),
 np.int64(66),
 np.int64(68),
 np.int64(77),
 np.int64(84),
 np.int64(87),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(103),
 np.int64(113),
 np.int64(120),
 np.int64(127),
 np.int64(130),
 np.int64(135),
 np.int64(142),
 np.int64(145),
 np.int64(150),
 np.int64(151),
 np.int64(153),
 np.int64(154),
 np.int64(158),
 np.int64(164),
 np.int64(166),
 np.int64(167),
 np.int64(183),
 np.int64(189),
 np.int64(193),
 np.int64(194),
 np.int64(195),
 np.int64(197),
 np.int64(201),
 np.int64(202),
 np.int64(204),
 np.int64(213),
 np.int64(218),
 np.int64(221),
 np.int64(228),
 np.int64(235),
 np.int64(238),
 np.int64(239),
 np.int64(242),
 np.int64(24

In [14]:
df['Team_id'].value_counts()

Team_id
154     132
61       75
87       75
333      75
349      74
153      73
251      73
228      73
66       72
249      72
98       72
2636     71
201      71
194      71
99       71
290      71
252      71
142      70
2426     70
276      70
97       70
57       70
324      70
235      70
2633     70
2306     70
2655     70
197      70
344      69
213      69
221      69
2390     69
2032     69
145      69
309      69
2641     68
2116     68
2132     68
8        68
150      68
245      68
239      68
2        68
96       68
2335     68
2653     68
2628     68
326      67
130      67
2579     67
23       67
2567     67
6        67
2294     67
59       67
68       67
278      66
2483     66
238      66
135      66
5        66
2305     66
2348     66
275      66
103      66
52       66
277      66
30       65
2005     65
356      65
62       65
2247     65
2638     65
2439     65
21       65
183      65
158      65
164      65
58       65
77       65
2433     65
328      64
259     

In [15]:
df['opponent'].isna().sum()

np.int64(0)

In [16]:
df['opponent'].value_counts()

opponent
Bye                         762
Notre Dame                   66
Texas                        65
Georgia                      64
Alabama                      64
NC State                     64
Clemson                      62
Michigan                     62
Penn State                   62
Ohio State                   62
Louisville                   61
UTSA                         61
Tulane                       61
Iowa State                   60
Western Kentucky             60
Pittsburgh                   60
Oklahoma State               60
Oklahoma                     60
Iowa                         60
LSU                          59
Ole Miss                     59
Florida                      59
Louisiana                    59
Missouri                     59
Duke                         59
BYU                          58
Houston                      58
TCU                          58
UCF                          58
Syracuse                     58
Oregon                       58

In [17]:
opponent_unique = df['opponent'].unique()
opponent_unique = sorted(opponent_unique)
opponent_unique

['Abilene Christian',
 'Air Force',
 'Akron',
 'Alabama',
 'Alabama A&M',
 'Alabama State',
 'Albany',
 'Alcorn State',
 'App State',
 'Appalachian State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Arkansas State',
 'Arkansas-Pine Bluff',
 'Army',
 'Auburn',
 'Austin Peay',
 'BYU',
 'Ball State',
 'Baylor',
 'Bethune-Cookman',
 'Boise State',
 'Boston College',
 'Bowling Green',
 'Bryant',
 'Bucknell',
 'Buffalo',
 'Bye',
 'Cal Poly',
 'California',
 'Campbell',
 'Central Arkansas',
 'Central Connecticut',
 'Central Michigan',
 'Charleston Southern',
 'Charlotte',
 'Chattanooga',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colgate',
 'Colorado',
 'Colorado State',
 'Delaware',
 'Delaware State',
 'Duke',
 'Duquesne',
 'East Carolina',
 'East Tennessee State',
 'East Texas A&M',
 'Eastern Illinois',
 'Eastern Kentucky',
 'Eastern Michigan',
 'Eastern Washington',
 'Elon',
 'Florida',
 'Florida A&M',
 'Florida Atlantic',
 'Florida International',
 'Florida State',
 'Fordham',
 '

In [41]:
for i in df:
    print(i)

Team
date
Team_id
opponent
win_loss
OT
OT_num
pass
rush
rec
points_allowed
points_scored
point_differential
home_game
week
season
CONF
SOR
FPI
AP/CFP
SOS
GC
AVGWP


In [18]:
df['win_loss'].isna().sum()

np.int64(0)

In [19]:
df['win_loss'].value_counts()

win_loss
W      4103
L      3683
Bye     762
Name: count, dtype: int64

In [20]:
win_loss_unique = df['win_loss'].unique()
win_loss_unique = sorted(win_loss_unique)
win_loss_unique

['Bye', 'L', 'W']

In [21]:
df['OT'].isna().sum()

np.int64(0)

In [22]:
df['OT'].unique()

array([False,  True])

In [23]:
df['OT'].value_counts()

OT
False    8218
True      330
Name: count, dtype: int64

In [24]:
df['OT_num'].isna().sum()

np.int64(8218)

In [25]:
df['OT_num'].unique()

array([nan, ' ', '2', '4', '8', '6', '5', '3', '7', '9'], dtype=object)

In [26]:
df['OT_num'].value_counts()

OT_num
     202
2     91
4     16
3     12
8      2
6      2
5      2
9      2
7      1
Name: count, dtype: int64

In [27]:
unique_OT_num = df['OT_num'].unique()
unique_OT_num = sorted(unique_OT_num)
unique_OT_num

TypeError: '<' not supported between instances of 'str' and 'float'

In [28]:
df['pass'].isna().sum()

np.int64(16)

In [29]:
df['pass'].unique()

array([110.,  71.,  54.,  18.,   0., 115.,  79., 175.,  14.,  nan,  76.,
        68., 196., 138., 358., 121., 206., 395., 194., 378., 205., 250.,
       200., 374., 310., 209., 239., 215., 256., 109., 186., 164., 192.,
       424., 214., 326., 266., 293., 236., 212., 226., 299., 290., 217.,
       275., 219., 222., 246., 282., 157., 154., 155., 304., 161., 247.,
       291., 258.,  69., 422., 173., 268., 197., 301., 294., 126., 224.,
       284., 416., 229., 151., 240., 279., 149., 314., 207., 221., 341.,
       140., 317., 255., 345., 349., 170., 261., 167.,  97.,  35.,  44.,
       107., 102., 147.,  48.,  15.,  26., 190.,  17.,  65., 322., 165.,
       235., 213., 338., 176., 172., 286., 111., 262., 285., 168., 307.,
       211., 280., 331., 333., 248., 148., 324., 242., 274., 329., 204.,
       445., 188., 184., 119., 195., 158., 106., 234., 249., 254., 237.,
        51., 253., 303., 171.,  88., 313., 201., 390.,  55., 185.,  82.,
       127., 309., 257., 210., 264., 260., 193., 13

In [30]:
unique_pass = df['pass'].unique()
unique_pass = sorted(unique_pass)
unique_pass

[np.float64(0.0),
 np.float64(14.0),
 np.float64(15.0),
 np.float64(17.0),
 np.float64(18.0),
 np.float64(26.0),
 np.float64(35.0),
 np.float64(44.0),
 np.float64(48.0),
 np.float64(51.0),
 np.float64(54.0),
 np.float64(55.0),
 np.float64(57.0),
 np.float64(58.0),
 np.float64(59.0),
 np.float64(61.0),
 np.float64(62.0),
 np.float64(65.0),
 np.float64(66.0),
 np.float64(67.0),
 np.float64(68.0),
 np.float64(69.0),
 np.float64(70.0),
 np.float64(71.0),
 np.float64(76.0),
 np.float64(79.0),
 np.float64(82.0),
 np.float64(84.0),
 np.float64(87.0),
 np.float64(88.0),
 np.float64(91.0),
 np.float64(92.0),
 np.float64(95.0),
 np.float64(96.0),
 np.float64(97.0),
 np.float64(102.0),
 np.float64(103.0),
 np.float64(106.0),
 np.float64(107.0),
 np.float64(109.0),
 np.float64(110.0),
 np.float64(111.0),
 np.float64(115.0),
 np.float64(116.0),
 np.float64(119.0),
 np.float64(121.0),
 np.float64(123.0),
 np.float64(124.0),
 np.float64(125.0),
 np.float64(126.0),
 np.float64(127.0),
 np.float64(129.

In [31]:
df['pass'].value_counts()

pass
0.0      762
196.0     43
280.0     41
202.0     41
192.0     41
203.0     40
219.0     40
194.0     39
178.0     39
209.0     39
230.0     38
254.0     38
191.0     37
166.0     37
263.0     37
169.0     37
214.0     37
239.0     37
255.0     37
182.0     37
175.0     36
208.0     36
247.0     36
244.0     36
152.0     36
201.0     36
256.0     36
193.0     36
238.0     35
174.0     35
268.0     35
173.0     35
257.0     35
137.0     35
176.0     35
189.0     35
165.0     34
225.0     34
167.0     34
206.0     34
269.0     34
236.0     34
200.0     34
227.0     34
190.0     34
207.0     34
161.0     34
217.0     33
141.0     33
151.0     33
233.0     33
204.0     32
228.0     32
186.0     32
287.0     32
234.0     32
188.0     32
259.0     32
195.0     32
212.0     32
156.0     31
221.0     31
198.0     31
140.0     31
179.0     31
158.0     31
162.0     31
147.0     31
148.0     31
240.0     31
248.0     30
223.0     30
270.0     30
205.0     30
265.0     30
220.0     30
183.0  

In [61]:
for i in df:
    print(i)

Team
date
Team_id
opponent
win_loss
OT
OT_num
pass
rush
rec
points_allowed
points_scored
point_differential
home_game
week
season
CONF
SOR
FPI
AP/CFP
SOS
GC
AVGWP


In [32]:
df['rush'].isna().sum()

np.int64(1)

In [33]:
df['rush'].unique()

array([ 97.,  63.,  50.,  71.,   0.,  54.,  29., 103.,  60.,  61., 120.,
       107., 125.,  42.,  12., 109.,  49.,  19.,  73.,  69.,  68.,  56.,
       113., 102., 140.,  75., 117.,  45.,  79., 104., 185.,  43.,  28.,
        40.,  80.,  47.,  55., 148., 124., 115., 127., 108., 170., 143.,
        62., 182., 158., 153., 147., 177., 262., 106., 112.,  48.,  72.,
        20., 149., 101.,  26.,  37., 175.,  87.,  81.,  52.,  78.,  30.,
       130.,  89., 114.,  99.,  83., 160., 145., 152., 137., 136., 171.,
        53.,  67.,  91.,  57., 278.,  13.,  94.,  65.,  76.,  32.,  21.,
        31.,  82., 196., 116., 142., 192., 123., 267., 259., 186., 217.,
       128., 209., 159., 169., 226.,  85.,  74.,  51.,  64.,  90., 198.,
        93.,  22., 161.,  36., 150.,  15.,  86.,  38., 126., 119.,  88.,
        33.,  35.,  84., 151., 110., 118.,  58., 164.,  59., 105., 154.,
        41.,  66.,  44., 100.,  92.,  24., 132., 138.,  39.,  11.,  25.,
       156.,  77., 122., 111., 166.,  18., 220., 13

In [34]:
df['rush'].value_counts()

rush
0.0      762
60.0      90
67.0      85
68.0      83
49.0      83
57.0      82
63.0      82
64.0      80
71.0      80
76.0      80
78.0      80
80.0      79
82.0      78
65.0      78
54.0      77
74.0      77
87.0      77
69.0      77
52.0      77
39.0      76
53.0      75
104.0     75
62.0      75
66.0      74
75.0      74
83.0      74
73.0      73
81.0      73
55.0      73
42.0      73
58.0      71
43.0      70
61.0      70
50.0      69
48.0      69
79.0      69
45.0      69
70.0      69
84.0      68
72.0      68
56.0      67
47.0      66
86.0      65
51.0      64
94.0      64
59.0      63
95.0      63
89.0      63
111.0     63
77.0      62
96.0      62
113.0     60
100.0     60
106.0     60
102.0     59
41.0      59
101.0     58
91.0      58
85.0      58
38.0      57
97.0      57
88.0      56
37.0      55
35.0      55
31.0      54
46.0      54
36.0      53
40.0      53
103.0     51
117.0     51
108.0     51
99.0      51
107.0     50
118.0     50
32.0      50
93.0      50
33.0   

In [35]:
df['rec'].isna().sum()

np.int64(14)

In [36]:
df['rec'].unique()

array([ 68.,  21.,  36.,  18.,   0., 106.,  45.,  82.,  51.,  52.,  11.,
        nan,  76.,  41.,  59.,  55., 125.,  56.,  61.,  78., 168.,  98.,
        57., 107., 139., 177.,  89.,  73., 111.,  50.,  81.,  60.,  80.,
       129.,  58., 103.,  85.,  94.,  96., 121., 157., 162., 176.,  91.,
        99., 120., 117.,  84., 108., 143.,  35., 304.,  38., 138., 161.,
       202., 102.,  70., 115., 164.,  53., 137., 132.,  74., 135., 128.,
        37., 179., 172., 193.,  48.,  69.,  40.,  22.,  44.,  47.,  27.,
        24.,   8.,   9.,  29.,  72., 156.,  95., 104., 116., 112., 171.,
       148., 119.,  43.,  66.,  75., 101.,  90.,  92.,  62.,  67.,  79.,
        49.,  42., 145.,  86., 213.,  32., 131.,  33.,  71.,  63.,  54.,
       109.,  25., 118., 153., 205., 100.,  83.,  46., 127., 130., 149.,
        39.,  87., 198., 110., 175.,  31.,  65., 158., 140.,  88.,  20.,
       188., 187.,  28.,  64., 141.,  97., 295., 235., 134.,  93., 173.,
       113.,  34.,  77., 197., 165.,  30., 167., 13

In [37]:
df['rec'].value_counts()

rec
0.0      762
81.0     107
68.0     103
76.0     100
75.0      98
60.0      96
72.0      96
84.0      96
89.0      95
70.0      95
73.0      95
78.0      89
67.0      88
59.0      87
54.0      87
74.0      86
85.0      85
63.0      85
77.0      85
65.0      84
64.0      84
61.0      83
69.0      83
80.0      83
79.0      83
66.0      79
102.0     79
91.0      78
93.0      78
53.0      77
83.0      77
98.0      77
71.0      76
86.0      76
48.0      75
87.0      74
57.0      74
50.0      74
58.0      73
62.0      73
96.0      72
55.0      72
90.0      71
88.0      70
82.0      69
44.0      68
94.0      68
100.0     67
101.0     67
52.0      66
56.0      65
105.0     65
92.0      64
99.0      64
43.0      64
47.0      62
45.0      61
49.0      60
42.0      60
103.0     60
46.0      57
51.0      57
106.0     57
95.0      55
116.0     55
36.0      55
39.0      54
104.0     54
107.0     53
97.0      53
108.0     52
117.0     52
115.0     51
112.0     49
110.0     49
118.0     49
120.0   

In [38]:
df['points_allowed'].isna().sum()

np.int64(0)

In [39]:
df['points_allowed'].value_counts()

points_allowed
0     934
24    433
17    382
31    372
14    367
21    338
20    322
27    320
10    307
7     287
38    285
28    278
34    276
13    246
35    232
41    194
45    187
30    183
23    182
42    178
3     165
37    134
16    125
49    105
26    103
52    100
33     99
6      96
19     92
48     91
44     84
29     83
40     70
22     69
25     55
32     55
9      54
56     52
15     51
12     48
39     47
36     46
55     44
18     42
43     40
59     38
51     34
47     32
50     25
63     24
46     19
11     18
62     14
66     13
54     13
53     13
58     12
70      7
8       6
61      4
69      4
73      3
77      3
5       2
71      2
57      2
65      2
60      2
2       2
64      1
Name: count, dtype: int64

In [40]:
df['points_allowed'].unique()

array([ 0,  6, 17, 31, 34, 52, 21, 20, 28, 19, 30, 49, 50, 27, 14, 41, 29,
       16, 10, 40, 25, 24, 13,  7, 66, 48, 38, 26, 39, 23, 56,  3, 63, 55,
       62, 37, 45, 35, 51, 42, 43, 44, 18, 47, 15,  9, 36, 33, 46, 59, 53,
       11,  8, 22, 12, 32, 71,  5, 58, 61, 54, 70, 73, 69, 77, 57, 65, 60,
       64,  2])

In [41]:
df['points_scored'].isna().sum()

np.int64(0)

In [42]:
df['points_scored'].unique()

array([28, 21,  7,  3,  0, 19, 37, 13, 36, 22, 31,  6, 10, 17, 25, 20, 24,
       30, 16, 38, 63, 42, 41, 35, 27, 34, 52, 14, 33, 45, 49, 48, 61, 23,
       26, 12, 70, 58, 39, 18,  9, 44, 32, 29, 73, 43, 59, 56, 62, 15, 51,
       46, 66, 55, 40, 11, 50, 77, 47, 54,  5, 53, 76, 69, 87, 71,  8, 57,
       72, 81, 65, 78, 64, 68, 60,  2])

In [43]:
df['points_scored'].value_counts()

points_scored
0     873
24    431
31    391
17    350
21    329
27    328
14    328
38    308
20    306
34    287
28    284
10    257
35    240
13    233
7     222
45    216
41    212
42    197
30    183
23    180
37    137
3     126
49    124
16    119
52    115
48    108
26    100
33     99
44     96
19     89
6      88
29     84
40     81
56     73
22     69
32     57
59     56
25     55
55     52
36     51
9      47
39     46
12     45
43     43
15     42
18     41
51     39
63     35
47     35
50     29
66     26
62     21
46     20
11     19
54     17
58     15
53     14
70     13
69     11
65      7
73      7
57      6
77      6
8       6
61      3
71      3
64      3
60      3
2       2
76      2
5       2
72      2
87      1
81      1
78      1
68      1
Name: count, dtype: int64

In [44]:
df['point_differential'].isna().sum()

np.int64(0)

In [45]:
df['point_differential'].unique()

array([ 28,  15, -10, -28,   0, -12, -27, -15,  -8, -17,   8,   3,  11,
       -46, -20, -32, -43,   4,  -7,   7, -11, -13,  21,  63,  26,  32,
        -5,   2,  34,  14,  29,  45, -21,  -6, -34, -14,  -9,  10,   5,
        42,  41,  22,  12, -24,  13, -22, -42, -44,  24,  70,  -4,  33,
       -45,  16, -36,  35,  17,  23, -35, -18, -62,  -3, -56, -25,  56,
         1,   6,  20, -16,  18,  25, -38,  31, -31,  36,  19,  37,  -1,
        -2, -39, -23, -26,  46, -19, -29,  27,  52, -52,  39,  47,  38,
       -49,  48,   9,  74,  49,  66,  40, -33, -71, -41,  30,  62,  43,
       -37,  44,  51, -48,  59,  76, -59, -66,  77, -55, -30,  71,  55,
       -47, -51,  54,  58, -63, -40, -73,  57,  53, -60,  60, -50,  73,
        69, -53,  65,  50,  68, -57, -58])

In [46]:
df['point_differential'].value_counts()

point_differential
 0     762
 3     400
-3     384
 7     323
-7     317
 10    180
 14    174
-10    171
-14    168
 17    161
 21    159
-17    152
 4     139
-21    136
-4     135
-2     130
 2     129
-6     127
 6     124
 28    122
 1     121
-1     118
 8     118
-8     113
 24    107
-28    104
-24    102
 11     94
 18     91
 5      91
-11     87
-5      87
 31     86
-18     81
-13     77
 35     76
 13     75
 20     73
-31     71
-20     68
 15     66
-15     64
 27     64
 25     63
-27     60
 32     60
 12     59
-35     59
-25     57
 34     57
-12     56
 23     55
 38     52
 42     51
-9      49
 22     48
-32     48
 9      47
-19     46
 19     46
 16     46
-23     45
-22     44
-34     44
 26     43
-16     43
-38     41
 29     41
 45     39
-26     38
-29     37
-42     35
 33     32
 49     32
 37     32
-33     29
 41     28
 52     28
 30     28
 39     27
-45     26
 56     25
-30     24
-37     23
-49     21
 40     20
 46     20
-39     19
-41     18
 3

In [47]:
df['home_game'].isna().sum()

np.int64(0)

In [48]:
df['home_game'].unique()

array(['TRUE', 'FALSE', 'Bye'], dtype=object)

In [49]:
df['home_game'].value_counts()

home_game
TRUE     4420
FALSE    3366
Bye       762
Name: count, dtype: int64

In [50]:
df['week'].isna().sum()

np.int64(0)

In [51]:
df['week'].unique()

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17,
       18,  0, -2, -1, -6, -5, -8, -7, -4, -3, -9])

In [83]:
df['week'].value_counts().sort_index()

week
-9       1
-8       8
-7      20
-6      37
-5      56
-4      68
-3      73
-2      85
-1      93
 0     105
 1     641
 2     645
 3     650
 4     650
 5     650
 6     650
 7     525
 8     525
 9     525
 10    525
 11    524
 12    523
 13    492
 14    333
 15    115
 16     19
 17      6
 18      4
Name: count, dtype: int64

In [52]:
df['season'].isna().sum()

np.int64(0)

In [53]:
df['season'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [54]:
df['season'].value_counts()

season
2024    1932
2023    1794
2022    1779
2021    1761
2020    1282
Name: count, dtype: int64

In [55]:
df['CONF'].isna().sum()

np.int64(0)

In [56]:
df['CONF'].unique()

array(['Mountain West', 'MAC', 'SEC', 'Sun Belt', 'Big 12', 'American',
       'ACC', 'CUSA', 'Big Ten', 'FBS Indep.', 'Pac-12'], dtype=object)

In [57]:
df['CONF'].value_counts()

CONF
SEC              1007
ACC              1003
Big Ten           974
Big 12            824
American          808
Sun Belt          790
Mountain West     769
CUSA              739
MAC               694
Pac-12            593
FBS Indep.        347
Name: count, dtype: int64

In [58]:
df['SOR'].isna().sum()

np.int64(0)

In [59]:
df['SOR'].unique()

array([108, 111,  17,  90,  14,  88,  40,  65,  27,  64, 122,  39,  16,
        52,  91,  62,   7,  76, 118,  97,  69,  25, 105,  30,  71,  33,
        81, 113, 130,  20, 125, 106, 102,   4,  56, 115,  44, 107,  74,
        11,   8,  41,  15,  83,  66,  57,  28, 133, 134,  59,  89,  51,
       120,  23,  10,  34,  77, 131,  29,  67,  21,  61,  22, 126,  37,
       104,  12,  32,  79,  46, 123, 109, 127,  86, 100,  73,  82,   3,
        45,   1,  42,  94,  99,  13,   2, 101,   6,  54, 116, 110,  53,
        48, 124,  93,  18,  92,  19,  78, 132,  98,  26,  35, 117,   9,
        24,   5,  75,  43,  80, 114,  50, 128, 121,  87,  47,  63,  96,
        31,  38, 112,  72, 129,  85,  36,  68,  60,  95,  49,  70,  58,
        84, 103,  55, 119])

In [60]:
df['SOR'].value_counts()

SOR
119    120
1       81
6       76
3       76
5       75
14      74
2       74
4       74
15      73
8       73
38      73
16      72
20      72
27      72
43      71
12      71
87      71
49      71
17      71
21      71
10      71
34      71
70      71
63      70
7       70
36      70
30      70
61      69
19      69
42      69
105     69
28      69
58      68
18      68
54      68
32      68
46      68
33      68
103     68
55      68
72      68
90      67
91      67
9       67
26      67
44      67
110     67
23      67
56      67
106     67
66      67
40      67
13      66
92      66
31      66
62      66
97      66
94      66
48      66
116     66
114     66
75      66
93      66
102     66
85      66
37      66
71      66
24      66
76      65
11      65
86      65
60      65
25      64
83      64
74      64
109     64
45      64
79      64
89      64
59      64
52      64
108     63
22      63
118     63
112     63
95      63
81      63
41      63
115     63
51      63
98    

In [61]:
df['FPI'].isna().sum()

np.int64(0)

In [62]:
df['FPI'].unique()

array([106, 124,   4,  97,  21,  80,  34, 112,  50,  31, 126,  36,  27,
        52,  83, 104,  25,  54, 123, 121,  53,  14, 100,  23, 105,  60,
        90, 119, 116,  19, 117,  88,  81,   7,  78, 109,  41, 115,  79,
        42,  10,  22,  26,  72,  59,  33,  24, 131, 134,  48, 102,  73,
       111,  12,  18,  58,  69, 125,  57,  74,  11,  82,  29, 128,  28,
        66,  20,  61,  71,  38, 103, 107, 130,  64,  95,  86,  89,   3,
        70,   1,  30,  68,  77,   5,   8,  96,   6,  56, 120, 101,  51,
        94, 122,  91,  13,  67,  15,  84, 132,  93,  49,  35, 127,   9,
        16,   2,  62,  44,  87,  98,  32, 133, 118,  45,  55,  76, 114,
        40,  17, 110,  46, 129,  85,  39,  75,  37,  92,  43,  65,  63,
        99, 108,  47, 113])

In [63]:
df['AP/CFP'].isna().sum()

np.int64(0)

In [64]:
df['AP/CFP'].unique()

array(['--', '11', '12', '22', '9', '17', '16', '23', '2', '20', '8',
       '18', '25', '13', '19', '5', '6', '14', '1', '4', '10', '15', '21',
       '7', '3', '24'], dtype=object)

In [65]:
df['SOS'].isna().sum()

np.int64(0)

In [66]:
df['SOS'].unique()

array([117,  55,  20, 101,  39,  58,  24,  95,  89,  33,  91,  48,  67,
        53,  82, 115,  44,  71, 128,  85,  61,  28, 122,  65,  77,  49,
       126, 130, 131,   7, 106,  25,  98,   1,  79, 104,  23, 118,  50,
        30,  35,  38,  42, 113, 129,  43,  51, 133,  59,   8, 134, 110,
       120,  31,  14,  64,  22,  84, 111,  78,  56,  26,   5,  92,  45,
         3,  34,  74,  66,  15,  86, 123, 112,  90, 103,  83,  40,   4,
       116,   2,   9,  46,  99,  37,  19,  88,  10,  57,  11, 100,  62,
       124, 109, 119,  41, 108,  21,  73, 114,  29,  75,  68,  96,  16,
        13,   6, 121,  63, 127, 107,  81, 132, 102,  52,  18, 125,  69,
        87,  27,  93,  72,  94,  76,  17,  36,  47,  60,  12, 105,  54,
        80,  70,  32,  97])

In [67]:
df['GC'].isna().sum()

np.int64(0)

In [68]:
df['GC'].unique()

array([115, 110,   7, 117,  19,  92,  27,  97,  25,  47, 111,  38,  22,
        55,  68,  86,  14,  62, 124, 118,  51,  10, 109,  44,  75,  60,
        95, 120, 121,  16, 105, 100,  67,  12,  87, 116,  36, 106,  81,
        34,   6,  29,  49,  98,  65,  24,  42,  54,  76, 114,  17,  15,
        40,  73, 119,  28,  83,  20,  59,  23,  26,  91,  39,  43,  84,
        21, 107, 122,  69, 101,  89,  72,   4,  58,   1,  35,  85,  82,
         3,   5,  96,   8,  66, 112,  93,  52,  79, 123,  94,  18,  70,
         9, 104,  88,  46,  30,  11,  13,   2,  56,  45,  80, 113,  48,
       108,  71,  57,  90,  99,  37,  31, 102,  50,  61,  33,  78,  32,
        74,  53,  63,  64,  77, 103,  41])

In [69]:
df['AVGWP'].isna().sum()

np.int64(0)

In [70]:
df['AVGWP'].unique()

array([100, 110,  12, 123,  24, 116,  47,  88,   4,  65, 109,  52,   9,
        62,  39,  57,  14,  71, 118, 122,  73,  10,  86,  50,  53,  74,
        64,  93,  98,  35,  72, 126,  45,  46,  80, 114,  66,  84, 117,
        36,   6,  32,  61,  58,  20,  37,  59, 129, 134,  92,  82,  44,
        83,  25,  34,  21, 111, 115,   8,  60,  22,  90,  51, 130,  31,
       128,  54,  23,  97,  30, 108, 106, 124,  75,  91,  69, 107,   5,
        18,   1,  77, 121,  79,   2,   7,  96,  13,  78, 133,  89,  49,
        42, 113,  70,  16,  41,  19,  95, 132, 119,  38,  28, 127,  15,
        26,   3,  11,  48,  43, 105,  27, 131, 102, 101, 103,  55, 104,
        17,  68,  99,  63, 120,  33,  67, 112,  40,  94,  85,  29,  81,
        56,  87,  76, 125])