In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('WeekByWeekRankings2020to2025.csv')
# df

In [3]:
df['AP_rank'].isna().sum()

np.int64(0)

In [4]:
df['AP_rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
df['Team'].isna().sum()

np.int64(0)

In [6]:
unique_team = df['Team'].unique()
unique_team = sorted(unique_team)
unique_team

['Air Force',
 'Alabama',
 'Appalachian State',
 'Arizona',
 'Arizona State',
 'Arkansas',
 'Army',
 'Auburn',
 'BYU',
 'Ball State',
 'Baylor',
 'Boise State',
 'Buffalo',
 'Cincinnati',
 'Clemson',
 'Coastal Carolina',
 'Colorado',
 'Duke',
 'Florida',
 'Florida State',
 'Fresno State',
 'Georgia',
 'Houston',
 'Illinois',
 'Indiana',
 'Iowa',
 'Iowa State',
 'James Madison',
 'Kansas',
 'Kansas State',
 'Kentucky',
 'LSU',
 'Liberty',
 'Louisiana',
 'Louisville',
 'Marshall',
 'Memphis',
 'Miami',
 'Michigan',
 'Michigan State',
 'Minnesota',
 'Mississippi State',
 'Missouri',
 'NC State',
 'Navy',
 'Nebraska',
 'North Carolina',
 'Northwestern',
 'Notre Dame',
 'Ohio State',
 'Oklahoma',
 'Oklahoma State',
 'Ole Miss',
 'Oregon',
 'Oregon State',
 'Penn State',
 'Pittsburgh',
 'SMU',
 'San Diego State',
 'San José State',
 'South Carolina',
 'Syracuse',
 'TCU',
 'Tennessee',
 'Texas',
 'Texas A&M',
 'Texas Tech',
 'Toledo',
 'Troy',
 'Tulane',
 'Tulsa',
 'UCF',
 'UCLA',
 'UNLV',
 '

In [7]:
df['Team'].value_counts()

Team
Georgia              79
Alabama              79
Ohio State           78
Oregon               74
Notre Dame           71
Penn State           64
Clemson              63
Michigan             62
Ole Miss             61
Texas                56
Oklahoma             56
Oklahoma State       52
Tennessee            50
Texas A&M            49
USC                  45
BYU                  43
Utah                 42
LSU                  42
Miami                40
Cincinnati           37
North Carolina       36
Kansas State         34
Iowa State           30
Washington           29
Iowa                 29
NC State             28
Florida              26
Missouri             26
Florida State        24
Wisconsin            24
SMU                  24
Coastal Carolina     22
Tulane               22
Wake Forest          22
Kentucky             21
UCLA                 21
Oregon State         21
Indiana              20
Pittsburgh           19
Louisville           19
Baylor               18
Auburn     

In [8]:
df['Week'].isna().sum()

np.int64(0)

In [9]:
df['Week'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
df['Week'].value_counts().sort_index()

Week
1     125
2     100
3     125
4     125
5     125
6     125
7     125
8     125
9     125
10    125
11    125
12    125
13    125
14    125
15    125
16    125
Name: count, dtype: int64

In [11]:
df['year'].isna().sum()

np.int64(0)

In [12]:
df['year'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [13]:
df['year'].value_counts()

year
2024    400
2023    400
2022    400
2021    400
2020    375
Name: count, dtype: int64