In [124]:
import pandas as pd
import numpy as np
# pd.reset_option('display.max_rows')
pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_csv('WeekByWeekRankings2020to2025.csv')
df_copy = df.copy()

In [ ]:
df1 = pd.read_csv('CollegeFootballRankings24to20.csv')
df_copy = df.copy()

In [123]:
headers = df.columns
print(headers)

Index(['AP_rank', 'Team', 'Week', 'year'], dtype='object')


In [105]:
df['AP_rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [144]:
df['AP_rank'].value_counts()
AP_rank_values = df['AP_rank'].value_counts()
AP_rank_sorted_values = AP_rank_values.sort_index(ascending = True)
print(AP_rank_sorted_values)

AP_rank
1     79
2     80
3     80
4     77
5     79
6     79
7     79
8     81
9     77
10    79
11    81
12    77
13    79
14    79
15    79
16    80
17    78
18    79
19    79
20    79
21    80
22    78
23    79
24    79
25    79
Name: count, dtype: int64


In [107]:
df['AP_rank'].isna().sum()

np.int64(0)

In [108]:
df['Team'].isna().sum()

np.int64(0)

In [109]:
df['Team'].unique()

array(['Georgia', 'Ohio State', 'Oregon', 'Texas', 'Alabama', 'Ole Miss',
       'Notre Dame', 'Michigan', 'Penn State', 'Florida State',
       'Missouri', 'LSU', 'Utah', 'Clemson', 'Tennessee', 'Oklahoma',
       'Kansas State', 'Oklahoma State', 'Miami', 'Texas A&M', 'Arizona',
       'NC State', 'USC', 'Kansas', 'Iowa', 'Louisville', 'Washington',
       'Iowa State', 'Nebraska', 'Memphis', 'UNLV', 'Illinois', 'BYU',
       'Indiana', 'Boise State', 'Pittsburgh', 'SMU', 'Army', 'Navy',
       'Vanderbilt', 'Washington State', 'Colorado', 'South Carolina',
       'Tulane', 'Arizona State', 'Syracuse', 'TCU', 'Oregon State',
       'North Carolina', 'Wisconsin', 'Texas Tech', 'Duke', 'UCLA',
       'Florida', 'Kentucky', 'Fresno State', 'Air Force',
       'James Madison', 'Liberty', 'Toledo', 'West Virginia', 'Baylor',
       'Michigan State', 'Wake Forest', 'Cincinnati', 'Arkansas',
       'Houston', 'Minnesota', 'Mississippi State', 'UCF',
       'Coastal Carolina', 'UTSA', 'Troy'

In [143]:
df['Team'].value_counts()
dfteam_values = df['Team'].value_counts()
dfteam_sorted_values = dfteam_values.sort_index(ascending = True)
print(dfteam_sorted_values)

Team
Air Force             3
Alabama              79
Appalachian State     1
Arizona               9
Arizona State         8
Arkansas             16
Army                 13
Auburn               18
BYU                  43
Ball State            1
Baylor               18
Boise State          11
Buffalo               2
Cincinnati           37
Clemson              63
Coastal Carolina     22
Colorado             10
Duke                  8
Florida              26
Florida State        24
Fresno State          5
Georgia              79
Houston               8
Illinois             14
Indiana              20
Iowa                 29
Iowa State           30
James Madison         7
Kansas                9
Kansas State         34
Kentucky             21
LSU                  42
Liberty              12
Louisiana            17
Louisville           19
Marshall              7
Memphis               8
Miami                40
Michigan             62
Michigan State       17
Minnesota             5
Mississippi

In [111]:
df['Week'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [112]:
df['Week'].isna().sum()

np.int64(0)

In [145]:
df['Week'].value_counts()
week_values = df['Week'].value_counts()
week_sorted_values = week_values.sort_index(ascending = True)
print(week_sorted_values)

Week
1     125
2     100
3     125
4     125
5     125
6     125
7     125
8     125
9     125
10    125
11    125
12    125
13    125
14    125
15    125
16    125
Name: count, dtype: int64


In [ ]:
df['year'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [146]:
df['year'].value_counts()
year_values = df['year'].value_counts()
year_sorted_values = year_values.sort_index(ascending = True)
print(year_sorted_values)

year
2020    375
2021    400
2022    400
2023    400
2024    400
Name: count, dtype: int64


In [116]:
df['year'].isna().sum()

np.int64(0)

In [129]:
headers1 = df1.columns
print(headers1)

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')


In [118]:
df1['Team'].unique()

array(['Air Force Falcons', 'Akron Zips', 'Alabama Crimson Tide',
       'App State Mountaineers', 'Arizona State Sun Devils',
       'Arizona Wildcats', 'Arkansas Razorbacks',
       'Arkansas State Red Wolves', 'Army Black Knights', 'Auburn Tigers',
       'Ball State Cardinals', 'Baylor Bears', 'Boise State Broncos',
       'Boston College Eagles', 'Bowling Green Falcons', 'Buffalo Bulls',
       'BYU Cougars', 'California Golden Bears',
       'Central Michigan Chippewas', 'Charlotte 49ers',
       'Cincinnati Bearcats', 'Clemson Tigers',
       'Coastal Carolina Chanticleers', 'Colorado Buffaloes',
       'Colorado State Rams', 'Duke Blue Devils', 'East Carolina Pirates',
       'Eastern Michigan Eagles', 'Florida Atlantic Owls',
       'Florida Gators', 'Florida International Panthers',
       'Florida State Seminoles', 'Fresno State Bulldogs',
       'Georgia Bulldogs', 'Georgia Southern Eagles',
       'Georgia State Panthers', 'Georgia Tech Yellow Jackets',
       "Hawai'i Rai

In [142]:
df1['Team'].value_counts()
team_values = df1['Team'].value_counts()
team_sorted_values = team_values.sort_index(ascending = True)
print(team_sorted_values)

Team
Air Force Falcons                 54
Akron Zips                        41
Alabama Crimson Tide              64
App State Mountaineers             9
Arizona State Sun Devils          49
Arizona Wildcats                  53
Arkansas Razorbacks               59
Arkansas State Red Wolves         56
Army Black Knights                60
Auburn Tigers                     60
BYU Cougars                       60
Ball State Cardinals              39
Baylor Bears                      58
Boise State Broncos               58
Boston College Eagles             57
Bowling Green Falcons             36
Buffalo Bulls                     39
California Golden Bears           52
Central Michigan Chippewas        38
Charlotte 49ers                   51
Cincinnati Bearcats               61
Clemson Tigers                    63
Coastal Carolina Chanticleers     50
Colorado Buffaloes                53
Colorado State Rams               50
Duke Blue Devils                  57
East Carolina Pirates            

In [120]:
df1['Team'].isna().sum()

np.int64(0)

In [131]:
df1['date'].isna().sum()

np.int64(0)

In [132]:
df1['date'].unique()

array(['Sat, Aug 31', 'Sat, Nov 9', 'Sat, Nov 30', 'Sat, Sep 14',
       'Sat, Sep 28', 'Sat, Oct 5', 'Sat, Sep 7', 'Sat, Oct 19',
       'Sat, Nov 2', 'Sat, Oct 12', 'Sat, Nov 23', 'Sat, Nov 16',
       'Sat, Sep 21', 'Sat, Oct 26', 'Fri, Oct 11', 'Sat, Dec 7',
       'Fri, Sep 13', 'Fri, Nov 15', 'Fri, Dec 27', 'Fri, Aug 30',
       'Sat, Dec 14', 'Fri, Dec 6', 'Sat, Dec 28', 'Fri, Nov 29',
       'Fri, Oct 25', 'Fri, Nov 1', 'Sat, Jan 4', 'Fri, Sep 6',
       'Fri, Oct 18', 'Fri, Nov 8', 'Sat, Dec 21', 'Fri, Dec 20',
       'Sat, Aug 24', 'Fri, Oct 4', 'Fri, Sep 20', 'Fri, Sep 27',
       'Fri, Nov 22', 'Fri, Jan 3', 'Fri, Jan 10', 'Sat, Oct 21',
       'Sat, Sep 9', 'Sat, Nov 18', 'Sat, Oct 28', 'Sat, Nov 4',
       'Sat, Sep 2', 'Fri, Sep 15', 'Fri, Nov 24', 'Sat, Dec 23',
       'Sat, Nov 11', 'Fri, Sep 22', 'Sat, Sep 30', 'Sat, Oct 14',
       'Sat, Sep 16', 'Sat, Oct 7', 'Sat, Sep 23', 'Sat, Nov 25',
       'Sat, Dec 2', 'Sat, Dec 9', 'Sat, Dec 30', 'Sat, Dec 16',
       'Fri, 

In [141]:
df1['date'].value_counts()
date_values = df1['date'].value_counts()
date_sorted_values = date_values.sort_index(ascending = True)
print(date_sorted_values)

date
Fri, Aug 30     10
Fri, Dec 1       4
Fri, Dec 11      6
Fri, Dec 16      4
Fri, Dec 17      4
Fri, Dec 18      8
Fri, Dec 2       6
Fri, Dec 20      6
Fri, Dec 22      2
Fri, Dec 23      5
Fri, Dec 25      2
Fri, Dec 27     10
Fri, Dec 29      8
Fri, Dec 3       4
Fri, Dec 30      9
Fri, Dec 31      9
Fri, Dec 4       1
Fri, Dec 6       6
Fri, Jan 1       8
Fri, Jan 10      2
Fri, Jan 3       4
Fri, Nov 1       6
Fri, Nov 10      4
Fri, Nov 11      6
Fri, Nov 12      4
Fri, Nov 13      6
Fri, Nov 15      8
Fri, Nov 17      4
Fri, Nov 18      4
Fri, Nov 19     10
Fri, Nov 20      8
Fri, Nov 22      6
Fri, Nov 24     26
Fri, Nov 25     25
Fri, Nov 26     31
Fri, Nov 27     18
Fri, Nov 29     28
Fri, Nov 3       4
Fri, Nov 4       6
Fri, Nov 5       4
Fri, Nov 6       5
Fri, Nov 8       9
Fri, Oct 1       6
Fri, Oct 11      6
Fri, Oct 13      6
Fri, Oct 14      4
Fri, Oct 15      8
Fri, Oct 16      4
Fri, Oct 18      8
Fri, Oct 2       4
Fri, Oct 20      2
Fri, Oct 21      4
Fri, Oc

In [121]:
df1['opponent'].unique()

array(['Merrimack', 'Fresno State', 'San Diego State', 'Baylor',
       'Wyoming', 'Navy', 'San José State', 'Colorado State', ' Army',
       'New Mexico', 'Nevada', 'Oregon State', 'South Carolina',
       ' Ohio State', 'Rutgers', 'Colgate', 'Bowling Green',
       'Western Michigan', 'Eastern Michigan', 'Ohio', 'Buffalo',
       'Oklahoma', 'Auburn', 'Western Kentucky', 'South Florida',
       'Wisconsin', ' Georgia', 'Vanderbilt', ' Tennessee', ' Missouri',
       ' LSU', 'Mercer', 'East Tennessee State', 'Georgia Southern',
       'Louisiana', 'East Carolina', 'Marshall', ' Clemson',
       'Old Dominion', 'James Madison', 'Georgia State', ' Utah',
       'Arizona', 'UCF', ' Kansas State', ' BYU', 'Mississippi State',
       'Texas Tech', 'Kansas', 'Cincinnati', 'Oklahoma State',
       ' Iowa State ', 'Colorado', 'Northern Arizona', 'Houston', 'TCU',
       'West Virginia', ' Arizona State', ' Ole Miss', 'Louisiana Tech',
       'Texas Tech ', ' Oklahoma State', 'UAB', ' Texas A

In [140]:
df1['opponent'].value_counts()
opponent_values = df1['opponent'].value_counts()
opponent_sorted_values = values.sort_index(ascending = True)
print(opponent_sorted_values)

opponent
 Air Force                   2
 Air Force                   1
 Alabama                    52
 Alabama                     7
 Appalachian State           1
 Arizona                     5
 Arizona State               5
 Arizona State               1
 Arkansas                    9
 Arkansas                    3
 Army                        5
 Army                        3
 Auburn                     10
 BYU                        27
 BYU                         2
 Baylor                     10
 Baylor                      2
 Boise State                12
 Boston College              1
 Cincinnati                 20
 Cincinnati                  2
 Clemson                    31
 Clemson                     8
 Coastal Carolina            9
 Coastal Carolina            1
 Colorado                    8
 Colorado                    1
 Duke                        5
 Florida                    19
 Florida                     2
 Florida State              16
 Florida State               3

In [137]:
df1['opponent'].value_counts()

opponent
Vanderbilt                  54
Hawai'i                     53
 Alabama                    52
Rutgers                     52
UTSA                        52
UL Monroe                   51
Boston College              51
North Texas                 51
 Ohio State                 51
UAB                         50
Maryland                    50
Nebraska                    50
Stanford                    50
Texas Tech                  50
Texas State                 50
South Carolina              50
Nevada                      50
Arkansas State              49
Syracuse                    49
Florida Atlantic            49
South Florida               49
Temple                      49
Virginia                    48
Purdue                      48
West Virginia               48
Western Kentucky            48
Wyoming                     47
Troy                        47
California                  47
Mississippi State           47
Houston                     47
Utah State                  47

In [147]:
df1['win_loss'].unique()

array(['W', 'L'], dtype=object)

In [148]:
df1['win_loss'].isna().sum()

np.int64(0)

In [158]:
df1['win_loss'].value_counts()
win_loss_values = df1['win_loss'].value_counts()
win_loss_sorted_values = win_loss_values.sort_index(ascending = True)
print(win_loss_sorted_values)

win_loss
L    3341
W    3716
Name: count, dtype: int64


In [153]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [154]:
df1['pass'].unique()

array(['71', '14', '76', '18', '115', '54', '175', '79', '0', '110', '68',
       '138', '358', '206', '395', '121', '196', '378', '164', '256',
       '200', '194', '374', '310', '209', '239', '215', '109', '186',
       '326', '290', '236', '424', '293', '214', '212', '217', '299',
       '154', '291', '161', '275', '247', '258', '69', '282', '157',
       '155', '304', '219', '268', '301', '422', '173', '224', '284',
       '197', '294', '126', '207', '221', '229', '341', '416', '151',
       '279', '266', '240', '314', '149', '317', '255', '140', '261',
       '349', '345', '167', '97', '170', '35', '44', '107', '15', '102',
       '147', '48', '65', '26', '190', '17', '165', '286', '235', '322',
       '176', '213', '338', '172', '211', '333', '262', '111', '285',
       '168', '307', '192', '248', '148', '324', '274', '222', '242',
       '329', '204', '119', '280', '188', '184', '195', '158', '249',
       '234', '254', '51', '253', '237', '201', '250', '88', '313', '303',
     

In [155]:
df1['pass'].isna().sum()

np.int64(0)

In [157]:
df1['pass'].value_counts()
pass_values = df1['pass'].value_counts()
sorted_pass_values = pass_values.sort_index(ascending = True)
print(sorted_pass_values)


pass
0              16
100            14
101            13
102            21
103            16
104            22
105            10
106            19
107            20
108            19
109            18
11              2
110            27
111            18
112            23
113            18
114            15
115            24
116            18
117            17
118             9
119            13
12              2
120            24
121            21
122            16
123            21
124            15
125            27
126            20
127            21
128            18
129            23
13              1
130            22
131            22
132            22
133            16
134            17
135            12
136            19
137            32
138            26
139            16
14              4
140            25
141            27
142            18
143            23
144            25
145            25
146            17
147            25
148            27
149            21
15   

In [159]:
df1['rush'].unique()

array(['63', '120', '125', '71', '54', '29', '50', '60', '61', '103',
       '107', '97', '19', '42', '109', '49', '73', '12', '68', '45',
       '104', '102', '140', '75', '117', '79', '185', '43', '47', '127',
       '148', '40', '55', '80', '108', '115', '158', '177', '147', '262',
       '182', '153', '170', '48', '106', '112', '20', '72', '87', '81',
       '149', '37', '62', '26', '175', '56', '52', '78', '28', '89', '30',
       '114', '130', '137', '83', '160', '145', '136', '171', '53', '152',
       '57', '67', '91', '278', '69', '31', '13', '94', '65', '76', '32',
       '192', '82', '116', '142', '196', '123', '113', '186', '209',
       '128', '267', '259', '226', '217', '169', '159', '21', '22', '74',
       '51', '64', '198', '93', '90', '36', '124', '99', '38', '86',
       '119', '101', '88', '33', '35', '110', '151', '118', '58', '59',
       '164', '84', '105', '126', '143', '154', '41', '66', '44', '100',
       '92', '24', '132', '138', '11', '39', '25', '156', '77

In [160]:
df1['rush'].isna().sum()

np.int64(0)

In [161]:
df1['rush'].value_counts()
rush_values = df1['rush'].value_counts()
rush_sorted_values = rush_values.sort_index(ascending = True)
print(rush_sorted_values)

rush
0          1
10         5
100       46
101       50
102       55
103       43
104       62
105       43
106       47
107       35
108       44
109       34
11         7
110       42
111       58
112       41
113       53
114       33
115       38
116       19
117       43
118       37
119       39
12         9
120       37
121       34
122       29
123       39
124       38
125       35
126       23
127       35
128       32
129       32
13         5
130       28
131       21
132       27
133       24
134       20
135       28
136       28
137       23
138       29
139       18
14         6
140       20
141       13
142       16
143       19
144       16
145       20
146       28
147       17
148       20
149       15
15        11
150       13
151       15
152       14
153       15
154       14
155       10
156       19
157       12
158       18
159       14
16        13
160       14
161        5
162       13
163       12
164       15
165       12
166       14
167        8
168    

In [162]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [163]:
df1['rec'].unique()

array(['21', '11', '76', '18', '106', '45', '36', '51', '52', '82', '0',
       '68', '56', '41', '55', '125', '78', '168', '61', '59', '98', '60',
       '111', '139', '177', '89', '73', '50', '81', '103', '157', '96',
       '129', '94', '58', '162', '121', '84', '143', '99', '176', '35',
       '117', '108', '91', '138', '161', '38', '304', '70', '115', '102',
       '202', '135', '128', '137', '164', 'III', '120', '132', '74',
       '179', '37', 'Jr.', '193', '172', '48', '40', '69', '22', '44',
       '47', '8', '85', '24', '29', '9', '53', '104', '72', '116', '156',
       '95', '119', '112', '43', '75', '101', '90', '62', '92', '67',
       '79', '42', '32', '57', '33', '86', '71', '54', '63', '66', '118',
       '153', '100', '205', '83', '127', '46', '149', '87', '39', '148',
       '145', '110', '130', '175', '158', '31', '65', '140', '20', '88',
       '188', '80', '28', '131', '97', '49', '235', '134', '93', '173',
       '113', '77', 'IV', '197', '165', 'Zee', '155', '133

In [164]:
df1['rec'].isna().sum()

np.int64(0)

In [165]:
df1['rec'].value_counts()
rec_values = df1['rec'].value_counts()
rec_sorted_values = rec_values.sort_index(ascending = True)
print(rec_sorted_values)

rec
0            14
10            2
100          55
101          59
102          64
103          41
104          42
105          54
106          47
107          46
108          36
109          35
11            3
110          43
111          35
112          44
113          42
114          33
115          46
116          43
117          39
118          38
119          32
12            2
120          35
121          34
122          26
123          32
124          18
125          30
126          35
127          38
128          31
129          27
13            2
130          27
131          20
132          22
133          24
134          28
135          29
136          24
137          34
138          22
139          26
14           11
140          28
141          18
142          17
143          21
144          10
145          12
146          17
147          13
148          14
149          13
15            7
150          14
151           5
152          17
153          12
154           7
155 

In [166]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [167]:
df1['points_allowed'].unique()

array([  6,  28,  20,  31,  34,  17,  21,  52,  19,   0,  50,  49,  27,
        30,  41,  24,  14,  16,  10,  40,  25,  13,   7,  29,  66,  26,
        23,  39,   3,  56,  63,  55, 414,  38,  42,  62,  37,  45,  35,
        43,  18,  47,  15,  48,   9,  33,  36,  46,  51,  59,  44, 202,
        53, 342,  11,   8,  22,  12, 428,  32,  71, 332,  58, 272,  61,
        70, 312,  54, 352,   5, 522,  73, 274, 452, 412, 432,  69,  77,
        57, 413, 242, 172, 382, 454, 482, 353, 124, 282, 402, 302, 372,
       393,  60, 224, 189,  64, 313, 132, 314,   2, 423,  65, 472, 212])

In [168]:
df1['points_allowed'].isna().sum()

np.int64(0)

In [169]:
df1['points_allowed'].value_counts()
points_allowed_values = df1['points_allowed'].value_counts()
points_allowed_sorted_values = points_allowed_values.sort_index(ascending = True)
print(points_allowed_sorted_values)

points_allowed
0      156
2        2
3      154
5        1
6       89
7      268
8        6
9       45
10     268
11      16
12      46
13     217
14     344
15      49
16     119
17     344
18      36
19      80
20     293
21     305
22      61
23     162
24     384
25      50
26      95
27     287
28     249
29      75
30     161
31     323
32      51
33      90
34     248
35     204
36      43
37     120
38     255
39      41
40      62
41     173
42     154
43      36
44      76
45     168
46      17
47      28
48      83
49      95
50      25
51      33
52      88
53      11
54      10
55      37
56      50
57       2
58      10
59      35
60       2
61       4
62      12
63      23
64       1
65       1
66      13
69       3
70       6
71       2
73       3
77       3
124      1
132      1
172      1
189      1
202      4
212      1
224      1
242      1
272      1
274      2
282      1
302      1
312      4
313      1
314      1
332      2
342      6
352      2
353      1
372   

In [170]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [171]:
df1['points_scored'].unique()

array([ 21,  36,  31,   3,  19,   7,  13,  37,  22,  28,   6,  17,  20,
        24,  25,  10,  30,  63,  42,  41,  35,  27,  34,  52,  38,  33,
        49,  48,  14,  45,  61,  23,  12,  26,  39, 312,  58,  18,  32,
         9,  44,  29,  73,  43,   0,  59,  62,  56,  15,  16,  46,  55,
        66,  40,  51,  11, 428,  50,  77,  47, 342, 332,  70, 352,  53,
        54, 202,   5,  76,  69, 522,  71, 414,   8,  72, 272, 274, 413,
        57, 432, 452, 412,  81, 242,  65,  78,  64, 577, 302, 454, 172,
       382, 402,  68, 372, 353, 124, 282,  60, 224, 212, 393, 189, 132,
       314, 313,   2, 423, 482, 472])

In [172]:
df1['points_scored'].isna().sum()

np.int64(0)

In [173]:
df1['points_scored'].value_counts()
points_scored_values = df1['points_scored'].value_counts()
points_scored_sorted_values = points_scored_values.sort_index(ascending = True)
print(points_scored_sorted_values)

points_scored
0      104
2        2
3      119
5        1
6       82
7      207
8        6
9       38
10     227
11      17
12      43
13     208
14     307
15      40
16     113
17     317
18      35
19      78
20     277
21     296
22      62
23     161
24     385
25      50
26      93
27     292
28     254
29      77
30     157
31     339
32      52
33      90
34     259
35     210
36      48
37     122
38     277
39      40
40      71
41     187
42     172
43      39
44      85
45     195
46      18
47      31
48      98
49     112
50      28
51      37
52     100
53      12
54      14
55      45
56      70
57       4
58      13
59      51
60       3
61       3
62      18
63      34
64       3
65       6
66      25
68       1
69       9
70      11
71       3
72       2
73       7
76       2
77       6
78       1
81       1
124      1
132      1
172      1
189      1
202      4
212      2
224      1
242      1
272      2
274      2
282      1
302      1
312      3
313      1
314    

In [174]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [175]:
df1['point_differential'].unique()

array([  15,    8,   11,  -28,  -12,  -27,  -10,   -8,  -17,  -15,    3,
         28,  -43,  -46,  -32,   -7,    4,  -20,  -11,  -21,   14,   63,
         26,   32,    7,   -5,    2,   34,   29,   45,   -9,   42,   10,
          5,   41,   21,  -24,   -6,  -22,   22,   12,   24,   13,  -44,
        -42,  273,   -4,   33,  -45,   16,  -36,   35,   17,   23,  -18,
        -35,   70, -371,  -14,  -25,  -62,   -3,  -56,   56,    6,    1,
         20,  -16,   25,  -38,   31,  -31,   19,   -1,   37,   18,   -2,
        -39,  -23,  -34,  -26,   46,  -19,   27,   52,  -52, -176,   39,
       -305,   36,   47,   38,  -13,  -49,   48, -384,    9,  384,  -29,
         74,   49,   66,   40,  305,  297,  309,  -33,  -71,   30,   62,
       -297,  -37,   43,   44, -242,  -48,  176,   59, -273,   76,  -59,
        -66,  468,  -55,  -30,   71,  371,   55,   51,  -47,  -51,   58,
       -309,  242, -468,  -40,  -63,  -41,  245,  370,  -73,   57,  302,
         53,  174,  386,  405,  -60, -278,   60,  3

In [177]:
df1['point_differential'].isna().sum()

np.int64(0)

In [178]:
df1['point_differential'].value_counts()
point_differential_values = df1['point_differential'].value_counts()
point_differential_sorted_values = point_differential_values.sort_index(ascending = True)
print(point_differential_sorted_values)

point_differential
-468      1
-431      2
-424      1
-407      1
-405      1
-401      2
-386      1
-384      1
-375      1
-371      1
-370      1
-369      1
-368      1
-359      1
-355      1
-352      1
-338      2
-332      1
-316      1
-309      2
-305      2
-302      3
-300      1
-297      2
-281      1
-280      1
-278      1
-273      3
-269      1
-248      1
-245      2
-242      1
-210      1
-200      1
-185      1
-179      1
-176      2
-174      1
-169      1
-152      1
-113      1
-110      1
-73       2
-71       1
-66       2
-63       3
-62       3
-60       2
-59       4
-58       1
-57       1
-56      11
-55       5
-53       6
-52      12
-51       3
-50       4
-49      20
-48       9
-47       4
-46      10
-45      23
-44      10
-43       3
-42      35
-41      16
-40       9
-39      18
-38      39
-37      23
-36      15
-35      52
-34      41
-33      29
-32      39
-31      67
-30      21
-29      34
-28      92
-27      52
-26      36
-25      

In [179]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [180]:
df1['home_game'].unique()

array([ True, False])

In [181]:
df1['home_game'].isna().sum()

np.int64(0)

In [182]:
df1['home_game'].value_counts()
home_game_values = df1['home_game'].value_counts()
home_game_sorted_values = home_game_values.sort_index(ascending = True)
print(home_game_sorted_values)

home_game
False    3128
True     3929
Name: count, dtype: int64


In [183]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [184]:
df1['season'].isna().sum()

np.int64(0)

In [185]:
df1['season'].unique()

array([2024, 2023, 2022, 2021, 2020])

In [186]:
df1['season'].value_counts()
df1_season_values = df1['season'].value_counts()
df1_season_sorted_values = df1_season_values.sort_index(ascending = True)
print(df1_season_sorted_values)

season
2020     973
2021    1507
2022    1517
2023    1517
2024    1543
Name: count, dtype: int64


In [187]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [188]:
df1['CONF'].unique()

array(['Mountain West', 'MAC', 'SEC', 'Sun Belt', 'Big 12', 'American',
       'ACC', 'CUSA', 'Big Ten', 'FBS Indep.', 'Pac-12'], dtype=object)

In [189]:
df1['CONF'].isna().sum()

np.int64(0)

In [190]:
df1['CONF'].value_counts()
CONF_values = df1['CONF'].value_counts()
CONF_sorted_values = CONF_values.sort_index(ascending = True)
print(CONF_sorted_values)

CONF
ACC              843
American         669
Big 12           703
Big Ten          837
CUSA             564
FBS Indep.       292
MAC              478
Mountain West    653
Pac-12           525
SEC              854
Sun Belt         639
Name: count, dtype: int64


In [191]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [192]:
df1['SOR'].unique()

array([108, 111,  17,  90,  14,  88,  40,  65,  27,  64, 122,  39,  16,
        52,  91,  62,   7,  76, 118,  97,  69,  25, 105,  30,  71,  33,
        81, 113, 130,  20, 125, 106, 102,   4,  56, 115,  44, 107,  74,
        11,   8,  41,  15,  83,  66,  57,  28, 133, 134,  59,  89,  51,
       120,  23,  10,  34,  77, 131,  29,  67,  21,  61,  22, 126,  37,
       104,  12,  32,  79,  46, 123, 109, 127,  86, 100,  73,  82,   3,
        45,   1,  42,  94,  99,  13,   2, 101,   6,  54, 116, 110,  53,
        48, 124,  93,  18,  92,  19,  78, 132,  98,  26,  35, 117,   9,
        24,   5,  75,  43,  80, 114,  50, 128, 121,  87,  47,  63,  96,
        31,  38, 112,  72, 129,  85,  36,  68,  60,  95,  49,  70,  58,
        84, 103,  55, 119])

In [193]:
df1['SOR'].isna().sum()

np.int64(0)

In [194]:
df1['SOR'].value_counts()
SOR_values = df1['SOR'].value_counts()
SOR_sorted_values = SOR_values.sort_index(ascending = True)
print(SOR_sorted_values)

SOR
1      67
2      61
3      65
4      65
5      62
6      65
7      61
8      61
9      59
10     58
11     50
12     59
13     57
14     60
15     58
16     61
17     61
18     59
19     58
20     61
21     59
22     54
23     56
24     54
25     55
26     57
27     59
28     53
29     52
30     61
31     54
32     59
33     58
34     58
35     52
36     58
37     56
38     56
39     38
40     57
41     51
42     58
43     61
44     55
45     51
46     60
47     48
48     53
49     57
50     50
51     53
52     54
53     46
54     60
55     57
56     56
57     53
58     56
59     57
60     53
61     52
62     50
63     61
64     50
65     43
66     50
67     49
68     52
69     49
70     57
71     58
72     53
73     51
74     57
75     56
76     56
77     48
78     54
79     51
80     45
81     55
82     55
83     49
84     47
85     55
86     52
87     59
88     43
89     52
90     51
91     53
92     57
93     57
94     53
95     48
96     49
97     57
98     49
99     50
100   

In [195]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [196]:
df1['FPI'].unique()

array([106, 124,   4,  97,  21,  80,  34, 112,  50,  31, 126,  36,  27,
        52,  83, 104,  25,  54, 123, 121,  53,  14, 100,  23, 105,  60,
        90, 119, 116,  19, 117,  88,  81,   7,  78, 109,  41, 115,  79,
        42,  10,  22,  26,  72,  59,  33,  24, 131, 134,  48, 102,  73,
       111,  12,  18,  58,  69, 125,  57,  74,  11,  82,  29, 128,  28,
        66,  20,  61,  71,  38, 103, 107, 130,  64,  95,  86,  89,   3,
        70,   1,  30,  68,  77,   5,   8,  96,   6,  56, 120, 101,  51,
        94, 122,  91,  13,  67,  15,  84, 132,  93,  49,  35, 127,   9,
        16,   2,  62,  44,  87,  98,  32, 133, 118,  45,  55,  76, 114,
        40,  17, 110,  46, 129,  85,  39,  75,  37,  92,  43,  65,  63,
        99, 108,  47, 113])

In [197]:
df1['FPI'].isna().sum()

np.int64(0)

In [198]:
df1['FPI'].value_counts()
FPI_values = df1['FPI'].value_counts()
FPI_sorted_values = FPI_values.sort_index(ascending = True)
print(FPI_sorted_values)

FPI
1      67
2      63
3      63
4      63
5      59
6      59
7      64
8      60
9      56
10     62
11     60
12     59
13     63
14     60
15     59
16     60
17     57
18     50
19     61
20     56
21     58
22     60
23     50
24     55
25     58
26     59
27     55
28     59
29     53
30     61
31     58
32     61
33     40
34     56
35     60
36     57
37     51
38     57
39     49
40     55
41     58
42     54
43     57
44     57
45     54
46     52
47     58
48     54
49     58
50     54
51     48
52     56
53     58
54     59
55     57
56     59
57     59
58     57
59     54
60     55
61     53
62     53
63     59
64     54
65     41
66     39
67     56
68     50
69     57
70     57
71     54
72     53
73     55
74     53
75     50
76     58
77     56
78     53
79     57
80     48
81     53
82     51
83     48
84     44
85     48
86     57
87     43
88     56
89     43
90     48
91     54
92     57
93     50
94     48
95     53
96     52
97     48
98     50
99     52
100   

In [199]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [200]:
df1['AP/CFP'].unique()

array(['--', '11', '12', '22', '9', '17', '16', '23', '2', '20', '8',
       '18', '25', '13', '19', '5', '6', '14', '1', '4', '10', '15', '21',
       '7', '3', '24'], dtype=object)

In [201]:
df1['AP/CFP'].isna().sum()

np.int64(0)

In [202]:
df1['AP/CFP'].value_counts()
AP_CFP_values = df1['AP/CFP'].value_counts()
AP_CFP_sorted_values = AP_CFP_values.sort_index(ascending = True)
print(AP_CFP_sorted_values)

AP/CFP
--    5489
1       66
10      64
11      56
12      59
13      60
14      59
15      57
16      61
17      68
18      60
19      57
2       66
20      57
21      60
22      68
23      67
24      85
25      60
3       63
4       66
5       61
6       62
7       64
8       59
9       63
Name: count, dtype: int64


In [203]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [204]:
df1['SOS'].unique()

array([117,  55,  20, 101,  39,  58,  24,  95,  89,  33,  91,  48,  67,
        53,  82, 115,  44,  71, 128,  85,  61,  28, 122,  65,  77,  49,
       126, 130, 131,   7, 106,  25,  98,   1,  79, 104,  23, 118,  50,
        30,  35,  38,  42, 113, 129,  43,  51, 133,  59,   8, 134, 110,
       120,  31,  14,  64,  22,  84, 111,  78,  56,  26,   5,  92,  45,
         3,  34,  74,  66,  15,  86, 123, 112,  90, 103,  83,  40,   4,
       116,   2,   9,  46,  99,  37,  19,  88,  10,  57,  11, 100,  62,
       124, 109, 119,  41, 108,  21,  73, 114,  29,  75,  68,  96,  16,
        13,   6, 121,  63, 127, 107,  81, 132, 102,  52,  18, 125,  69,
        87,  27,  93,  72,  94,  76,  17,  36,  47,  60,  12, 105,  54,
        80,  70,  32,  97])

In [205]:
df1['SOS'].isna().sum()

np.int64(0)

In [206]:
df1['SOS'].value_counts()
SOS_values = df1['SOS'].value_counts()
SOS_sorted_values = SOS_values.sort_index(ascending = True)
print(SOS_sorted_values)

SOS
1      63
2      63
3      60
4      60
5      61
6      62
7      62
8      62
9      60
10     61
11     61
12     59
13     60
14     55
15     57
16     60
17     58
18     61
19     59
20     60
21     60
22     58
23     62
24     57
25     57
26     59
27     57
28     61
29     57
30     53
31     59
32     58
33     59
34     57
35     59
36     56
37     55
38     55
39     54
40     59
41     56
42     62
43     56
44     60
45     58
46     56
47     59
48     51
49     53
50     53
51     51
52     56
53     55
54     59
55     51
56     53
57     60
58     58
59     49
60     52
61     51
62     59
63     56
64     52
65     53
66     47
67     54
68     57
69     57
70     54
71     51
72     53
73     55
74     59
75     59
76     54
77     53
78     56
79     52
80     54
81     44
82     55
83     55
84     56
85     53
86     54
87     53
88     51
89     48
90     52
91     39
92     52
93     55
94     47
95     54
96     59
97     55
98     48
99     39
100   

In [207]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [208]:
df1['GC'].unique()

array([115, 110,   7, 117,  19,  92,  27,  97,  25,  47, 111,  38,  22,
        55,  68,  86,  14,  62, 124, 118,  51,  10, 109,  44,  75,  60,
        95, 120, 121,  16, 105, 100,  67,  12,  87, 116,  36, 106,  81,
        34,   6,  29,  49,  98,  65,  24,  42,  54,  76, 114,  17,  15,
        40,  73, 119,  28,  83,  20,  59,  23,  26,  91,  39,  43,  84,
        21, 107, 122,  69, 101,  89,  72,   4,  58,   1,  35,  85,  82,
         3,   5,  96,   8,  66, 112,  93,  52,  79, 123,  94,  18,  70,
         9, 104,  88,  46,  30,  11,  13,   2,  56,  45,  80, 113,  48,
       108,  71,  57,  90,  99,  37,  31, 102,  50,  61,  33,  78,  32,
        74,  53,  63,  64,  77, 103,  41])

In [209]:
df1['GC'].isna().sum()

np.int64(0)

In [210]:
df1['GC'].value_counts()
GC_values = df1['GC'].value_counts()
GC_sorted_values = GC_values.sort_index(ascending = True)
print(GC_sorted_values)

GC
1       67
2       66
3       59
4       62
5       61
6       63
7       59
8       61
9       60
10      61
11      61
12      60
13      61
14      54
15      57
16      61
17      58
18      59
19      55
20      52
21      54
22      57
23      55
24      57
25      61
26      53
27      60
28      53
29      56
30      54
31      53
32      58
33      56
34      50
35      53
36      56
37      59
38      54
39      53
40      61
41      55
42      59
43      58
44      43
45      53
46      62
47      55
48      57
49      59
50      53
51      50
52      49
53      53
54      56
55      39
56      56
57      54
58      46
59      60
60      58
61      58
62      60
63      58
64      49
65      58
66      50
67      55
68      54
69      52
70      52
71      50
72      54
73      55
74      34
75      60
76      56
77      58
78      51
79      52
80      51
81      52
82      57
83      52
84      48
85      58
86      41
87      51
88      57
89      47
90      47
91     

In [211]:
df1.columns

Index(['Team', 'date', 'opponent', 'win_loss', 'pass', 'rush', 'rec',
       'points_allowed', 'points_scored', 'point_differential', 'home_game',
       'season', 'CONF', 'SOR', 'FPI', 'AP/CFP', 'SOS', 'GC', 'AVGWP'],
      dtype='object')

In [212]:
df1['AVGWP'].unique()

array([100, 110,  12, 123,  24, 116,  47,  88,   4,  65, 109,  52,   9,
        62,  39,  57,  14,  71, 118, 122,  73,  10,  86,  50,  53,  74,
        64,  93,  98,  35,  72, 126,  45,  46,  80, 114,  66,  84, 117,
        36,   6,  32,  61,  58,  20,  37,  59, 129, 134,  92,  82,  44,
        83,  25,  34,  21, 111, 115,   8,  60,  22,  90,  51, 130,  31,
       128,  54,  23,  97,  30, 108, 106, 124,  75,  91,  69, 107,   5,
        18,   1,  77, 121,  79,   2,   7,  96,  13,  78, 133,  89,  49,
        42, 113,  70,  16,  41,  19,  95, 132, 119,  38,  28, 127,  15,
        26,   3,  11,  48,  43, 105,  27, 131, 102, 101, 103,  55, 104,
        17,  68,  99,  63, 120,  33,  67, 112,  40,  94,  85,  29,  81,
        56,  87,  76, 125])

In [213]:
df1['AVGWP'].isna().sum()

np.int64(0)

In [214]:
df1['AVGWP'].value_counts()
AVGWP_values = df1['AVGWP'].value_counts()
AVGWP_sorted_values = AVGWP_values.sort_index(ascending = True)
print(AVGWP_sorted_values)

AVGWP
1      67
2      62
3      67
4      59
5      57
6      62
7      57
8      55
9      60
10     50
11     54
12     55
13     63
14     56
15     58
16     48
17     62
18     54
19     54
20     56
21     62
22     58
23     60
24     49
25     60
26     57
27     57
28     59
29     56
30     59
31     55
32     57
33     56
34     58
35     56
36     55
37     58
38     41
39     54
40     55
41     58
42     43
43     54
44     51
45     51
46     50
47     52
48     49
49     57
50     57
51     55
52     55
53     51
54     42
55     59
56     56
57     55
58     53
59     60
60     53
61     58
62     56
63     55
64     54
65     46
66     55
67     56
68     45
69     53
70     53
71     55
72     56
73     59
74     52
75     49
76     54
77     60
78     49
79     53
80     52
81     51
82     50
83     45
84     48
85     54
86     50
87     50
88     55
89     56
90     58
91     58
92     55
93     52
94     48
95     51
96     54
97     53
98     52
99     58
100 